### ISSUE TITLE
Update User model to store identifiers for GCM and APNS pushes

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#101]
- `apns_token`: for users who are subscribed for Apple push notifications
- `gcm_registration_id`: for users who are subscribed for Android push notifications

**Comment by aaronschachter** [comment]
Could there potentially be a need to store multiple tokens across diff devices? You know, for when we build the iPad app.

**Comment by jonuy** [comment]
Oo good point. People could have multiple Android and iOS devices. Would it be sufficient to just store it as an array? `apns_tokens` and `gcm_registration_ids`?

**Comment by aaronschachter** [comment]
When a User logs out of an app, the app's device ID should be cleared from the User document.

**Comment by jonuy** [comment]
With #140 we're looking to handle this with Parse instead of handling it with GCM and APNS separately.
