### ISSUE TITLE
Create observers to listen for and do the actual submitting of push notifications to Parse

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#103]
While the observers in #102 determine whether or not a push notification should be sent, the idea is that those observers will then fire another event to actually send the messages to Parse. Even though Parse alone should help with sending notifications to both iOS and Android, I'm not sure if we'll want to create two separate observers to send notifications to the two separate platforms.

Parse documentation on sending pushes with their REST API:
- https://parse.com/docs/rest/guide#push-notifications-sending-pushes

Code from prototype that sent pushes to Parse:
- https://github.com/DoSomething/parse-prototype/blob/master/server/server.js

cc: @sbsmith86 @DFurnes

**Comment by sbsmith86** [comment]
Closing this. I have set up a service that connects Northstar to the Parse API and created Handlers that hold the logic for sending a push notifications when an event fires.
