### ISSUE TITLE
Create a Campaign Signup from a given Invite Code

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#116]
The mobile app allows a user to enter an Invite Code, which signs them up for a Campaign (without ever having to view the Campaign)

This is implemented in the [Drupal API](https://github.com/DoSomething/dosomething/pull/4243) by posting to a `/signups` resource, sending through the `source`.  @angaither, @jonuy , and I have been discussing changing this to a `signup_group_id` property instead of source.

The request (either on the Drupal end or Northstar end) needs to speak to the Hashery code @uy's been working on, in order to determine what the target Campaign id is. 

Example:
![join](https://cloud.githubusercontent.com/assets/1236811/7616607/904f3876-f95a-11e4-8614-e27e4e6fce27.png)

**Comment by jonuy** [comment]
@aaronschachter Given what's happening in here (https://github.com/DoSomething/northstar/pull/132), what you could do to submit an invite code is ...

1. Enter invite code, decode from words to actual signup group id with the Hashery library
2. After talking to design, the indication is that we'll need to display in the app the campaign name and some people in the group. So `GET /signup-group/:group_id` to get that info and find out if it's actually a valid ID.
3. Display the people and the campaign name. The user does their own sort of verification given that information.
4. The response from `GET /signup-group/:id` includes the campaign id. That can then be used on the actual signup submission:
`POST api.ds.org/v1/campaigns/:campaign_id/signup` with body: `{ source: <group_id> }`

**Comment by aaronschachter** [comment]
Ah ok. So.. we never needed the POST in https://github.com/DoSomething/dosomething/pull/4243 :hushed:

**Comment by jonuy** [comment]
Closing this since #132 got merged in.
