### ISSUE TITLE
Create Drupal User on registration

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#130]
Attempting to post to `users?create_drupal_user=true` to create a Drupal user but not having any luck.

Not sure if I'm making a mistake, or if this is a bug.  If just a mistake, please update wiki with example request.

Refs #117

**Comment by angaither** [comment]
@aaronschachter how/where are you testing this?

**Comment by aaronschachter** [comment]
Both with Paw (using `ios` as the DS application id) and from the Lets Do This iOS, where other requests have been working ok.  Is it working for you?

Tried URL's like:
https://api.dosomething.org/v1/users?create_drupal_user=1
https://api.dosomething.org/v1/users?create_drupal_user=true
and also by sending in the body params as well

**Comment by angaither** [comment]
It worked for me locally (at one point) I just tried testing locally now thought and I'm getting errors

**Comment by angaither** [comment]
convo in slack: 
> Dave Furnes: regarding ^, did we update environment variables when deploying the laravel 5 version? I think that might be it.
Jon Uy: i did a test just now registering through my local dev to Drupal staging and it’s working for me. so my guess is also the environment variables

You have to set `DRUPAL_API_URL` set in `.env`?

**Comment by DFurnes** [comment]
Yep, we should set this on the production environment.

**Comment by DFurnes** [comment]
Updated on Northstar production, so should be fixed!

**Comment by aaronschachter** [comment]
What is the proper way to make the request? Send a value? No value? @jonuy @angaither Would either of you mind updating the wiki with an example?

**Comment by jonuy** [comment]
At least when I've been doing it I've done `create_drupal_user=1`. The example in the wiki includes the param in the URL now. I just tried this on Northstar production and it worked.

**Comment by angaither** [comment]
@aaronschachter did this work for you?

**Comment by aaronschachter** [comment]
Just tested and confirmed!
