### ISSUE TITLE
Lazy Load login

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#136]
When requests come in from the mobile app... if the user doesn't exist, check in drupal if we can add more data to the user object

**Comment by angaither** [comment]
If a user as a DS.org account, and hasn't logged in to the site in a while, that user will not be in NS.
When they try to auth against NS, they will get a user doesn't exist error.

**Comment by angaither** [comment]
open questions: 
- hashed password from within drupal
- the api only returns the user id
- can we search drupal api by mobile number?

**Comment by jonuy** [comment]
Closing out this issue. We're planning on resolving this through Andrea's work and just biting the bullet and doing a massive import of all Drupal users into Northstar.

**Comment by angaither** [comment]
@jonuy the hashed password is still an open question though.

**Comment by chloealee** [comment]
@angaither should I also say that this PR fixes this issue? https://github.com/DoSomething/northstar/pull/229

**Comment by chloealee** [comment]
Oops just merged the other and forgot about this! Is it safe to close this issue now that #229 has been merged? @angaither @jonuy

**Comment by angaither** [comment]
yeah! safe to close
