### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#137]
Send Authenticated requests to drupal

[@jonuy can you add more info here!]

**Comment by jonuy** [comment]
The intent here is for kudos requests to be made from the mobile app and other client apps to Northstar. Northstar will then forward those requests onto Drupal on the user's behalf.

#### The Request

- `POST /kudos`
- **Body:**
```
{
  kudos_id: Number,
  reportback_item_id: Number
}
```
- **Header** should have a session token set to identify the user making the request.
- Northstar will receive the kudos request, figure out who it's from, and forward the request along to Drupal to process it.

#### The Drupals

See @weerd for more specific details on what may be needed to POST to Drupal. At the very least, you'll need to at least figure out the user's Drupal ID on Northstar and send that along in the POST requests to Drupal as well.
