### ISSUE TITLE
Rename /campaigns

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#138]
This route overlaps with `/campaigns` on drupal
Since we aren't asking for a list of campaigns with this route in NS, let's rename this to `user/campaigns`

**Comment by angaither** [comment]
Also, take this a a time to update any `nid` -> `id`

**Comment by chloealee** [comment]
hey @jonuy! Just to clarify, should the new endpoints be users/{session_token}/campaigns?

**Comment by angaither** [comment]
@chloealee I think the way it works now is the [session token is just in the header of the request](https://github.com/DoSomething/northstar/wiki/Spec#retrieving-a-users-activity-on-a-single-campaign). but I'm not sure if that's a standard we are keeping

**Comment by chloealee** [comment]
ahh ic! so would it be `users/{id}/campaigns` etc then? Because we'll need to specify which user we want to get campaign data on, right?

**Comment by angaither** [comment]
if the session key is passed in the header, that would be the user we want to update
