### ISSUE TITLE
Create a signup_created_at, reportback_created_at and reportback_updated_at attributes for user's campaign data

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#14]
Currently we have a `created_at` and `updated_at` value shared by campaign sign ups and report backs. We'll want to distinguish the timestamps on these actions, so...
- [ ] signup_created_at
- [ ] reportback_created_at
- [ ] reportback_updated_at

**Comment by jonuy** [comment]
In the same vein, we'll want to also figure out a solution for sign ups and report backs from a single user to the same campaign over the course of multiple years.

**Comment by jonuy** [comment]
I don't really remember what I was getting at here...

**Comment by angaither** [comment]
I think this was about getting multiple signup/rbs for the same node over many years
