### ISSUE TITLE
Document User.campaigns property

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#142]
What is this new thing?  What does the campaign _id reference?

https://github.com/DoSomething/northstar/wiki/Spec#retrieving-a-user

**Comment by DFurnes** [comment]
`_id` is the Northstar ID (naming convention from Mongo).

**Comment by DFurnes** [comment]
So, in the example from the spec linked above `"5430e850dt8hbc541c37tt3d"` is the unique ID assigned to a user object when it's created in the database by MongoDB.

**Comment by aaronschachter** [comment]
hey @DFurnes  - - The new thing I was referring to documenting specifically is the `campaigns` array property in the User response... which isn't documented in the the wiki.  But I didn't catch that the id/$id returned is just the User's mongo id in each Activity object... which answers my question (as did you) of what the `_id` is.

is there a specific reason its included in each activity object?

![screen shot 2015-06-09 at 7 44 27 am](https://cloud.githubusercontent.com/assets/1236811/8060652/722777a6-0e7b-11e5-923e-a85552813d8e.png)

**Comment by DFurnes** [comment]
Ah, gotcha! Each activity object has its own Mongo ID, which like the user's `_id` property is also generated automatically by MongoDB. The campaign object's `_id` refers to that specific activity object.

**Comment by DFurnes** [comment]
It could make sense to format `_id` as `id` for readability in API responses though, since the underscore is a little wonky looking. I don't think that'd be super hard to do.

**Comment by aaronschachter** [comment]
Ohh so, we do have Activity ID's in Mongo.  I was just looking at the first few characters and thought those id's were my user id.  So, yeah some updated wiki documentation would be sweet to close this issue out.

I'm trying to figure out the best way to query for this stuff in the mobile app.  Seems like I can always just use `GET users/[identifer/id` and don't really need the `campaigns` endpoint?

**Comment by DFurnes** [comment]
Yeah, I think that makes sense. A standalone `campaigns` endpoint is a bit confusing since Northstar only understands campaigns in relation to a user, rather than as a real standalone object.

**Comment by aaronschachter** [comment]
Would it make sense to just kill that `users/identifier/id/campaigns` path then, to simplify things?  Obviously doesn't block anything or is critical, but could potentially keep things leaner / meaner..

**Comment by DFurnes** [comment]
Yeah, I think that seems reasonable. My vote is to allow an application to query for a user ID via one of our other "source" ID fields, but after that always consider the Northstar ID to be the canonical ID.

@jonuy Thoughts?

**Comment by DFurnes** [comment]
Just made a [revision](https://github.com/DoSomething/northstar/wiki/Spec/_compare/b1287272281b5ed73f9fc6716d00af5adb31938b...102df8713b69969f748698994bc573d99798e165) to the wiki based on this issue's discussions. :smiley:

**Comment by DFurnes** [comment]
Oh, to clarify – I'd argue for getting rid of the `identifier` part of the URL and just always referring to a user by their Northstar ID. I would still keep the `users/{user_id}/campaigns` endpoint... I could see us wanting to perhaps truncate the campaigns listing in the main user object at some point if it becomes too long & having a "full" or separately paginated endpoint for that seems to make sense.

**Comment by aaronschachter** [comment]
Ah, good (end)point. 

How is the `user.campaigns` property sorted?  Just randomly?

Losing the `identifier` stuff sounds fine to me, but not sure about the reasons for adding in first place.

**Comment by jonuy** [comment]
I'm pretty sure that was the original idea behind the `/users/identifier/id/campaigns` endpoint, to provide only campaign data and cull out the rest of the user information that could be unnecessary depending on the application.

The `identifier` offers different applications different ways of getting user data. Like, on Aurora, I may only know an email or mobile number I want to query for, so `users/email/{email addr}` gets used. And then this sorta just spilled over into keeping that ability for the `/campaigns` resource.

And `user.campaigns` I think is sorted by the order it gets added to the doc. So in practice, should come in order of when signups happened.

**Comment by DFurnes** [comment]
Going to close this since the original issue was taken care of.

**Comment by aaronschachter** [comment]
Now that we're finally getting into displaying all of user's Reportback on iOS - I'm finding there is one big difference between the `user.campaigns` returned from `users/identifier/id` and the results in `users/identifer/id/campaigns`: The `reportback_data` property doesn't exist in the `user.campaigns` response.

Might be worth updating the [retrieving a User endpoint](https://github.com/DoSomething/northstar/wiki/Spec#retrieving-a-user) docs / response to clarify at some point. 

## users/identifier/id

![screen shot 2015-09-25 at 2 02 38 pm](https://cloud.githubusercontent.com/assets/1236811/10112252/641a630e-638e-11e5-9b98-a0fb8289eab2.png)


## users/identifier/id/campaigns

![screen shot 2015-09-25 at 2 03 06 pm](https://cloud.githubusercontent.com/assets/1236811/10112250/60c1483a-638e-11e5-8551-d999500ea0d7.png)
