### ISSUE TITLE
Make responses static and predictable

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#153]
In practice, I think this means we return all possible properties in our responses, at least providing a default empty response if there is no value.

For example, currently `GET /users/_id/abc123` could return us something like...
```
{
  "data": [
    {
      "_id": "abc123",
      "email": "test@example.com"
    }
  ]
}
```

But because `avatar` is a property that some users might have set, the suggestion is to also include that in the response even if it's not set for this user:
```
{
  "data": [
    {
      "_id": "abc123",
      "email": "test@example.com",
      "avatar": ""
    }
  ]
}
```

**Pros:**
- Will play nicer in Android dev with Retrofit/GSON conversion. Sounds like it'll make things easier on the iOS dev too.

**Cons:**
- Our Mongo backend intentionally doesn't store empty values for fields that aren't set. So if this were something we'd do, we either have to set empty values for these fields, or hardcode some application logic in Northstar to make sure it sends em back

Thoughts? Other pros and cons? @weerd @angaither @aaronschachter @eoji @toidiu @DFurnes

**Comment by weerd** [comment]
So the only thing I'd say against adding empty responses is that we could end up with objects with lots of empty items (I'm thinking the Campaigns response object specifically) and bloat the response. Particularly if it's an index listing with lots of campaigns or reportbacks, that's a lot of data with potentially lots of empty items that aren't used). 

My default has been to keep object responses nice and trimmed down, but if it's not ideal open to change it up.

I feel an empty string is going to complicate things.... I'd suggest `NULL` which is a valid data type and easier to test against than having to check for example, if the value `isset()` and `!empty()`...

**Comment by weerd** [comment]
Would it be possible as an alternative when for the Android app you need an empty array response, is that if the API responds with `NULL` or doesn't add the property, to check for that, and then if it's `NULL`or is not set, then transform it and change it to an empty array for the sake of the Java library that needs it that way.

I'm just debating if it's worth making changing how the response outputs so we can make a very specific library work with the data... just some food for thought.

**Comment by toidiu** [comment]
So the place where NULL falls apart is the following: If the user is NULL then on the client side we now have to do null checks before we access name.  if(user != null) { .... }
This really becomes a problem with ugly code when there are several nested items.


{
  "data": [
    {
      "_id": "abc123",
      "user": 
          { 
              "name" : "test@example.com" 
          }
      "avatar": ""
    }
  ]
}

**Comment by weerd** [comment]
wouldn't you need to do checks anyway if the user is an empty string?

If null you can also treat is as a boolean logic check:

```
if (user) {
 // user data exists, then lets roll
}

return false; // no user data, or however you wanna handle the 'no user'
```

**Comment by toidiu** [comment]
so in this case you would not need to check at all. because if the name is blank ("") then you would just set that as the name. But then you are talking default values, which I can see being a problem as well...

**Comment by weerd** [comment]
I dunno. A blank name in app seems weird: `Hello,  !` I'd actually potentially prefer an app deciding on a default value for things such as the name: `Hello, friend!`, etc.

*Dislcaimer: I'm also not sure how this is being used in the mobile app (thinking more about it via the website use), so I could just be speaking nonsense, haha :)

**Comment by DFurnes** [comment]
I think there's value in including empty fields for API discoverability (and simpler logic for checking and using nested resources). It seems like it would be convenient to be able to read a response and easily see what data is and isn't set for that object.

**Comment by aaronschachter** [comment]
I agree with @oidiu and @DFurnes's points here. missing properties feel more like a mystery to me more than conveying that we dont have a value for the property.

**Comment by weerd** [comment]
Yeah, I agree on that point and I can plan to make changes to *Campaign, Reportback, Reportback-Items, and Kudos* to roll w/ a all properties regardless of whether they have a value or not :) I mentioned the bloat issue as more of a note, and what caused us to decide to have missing properties in the first place.

Now it's just deciding on whether to go with `NULL`, empty string or something else. In regards to @DFurnes point for easily seeing what data is and isn't set for a property in an object, I think `NULL` gets that across the best.

**Comment by weerd** [comment]
Chatted with @jonuy for a bit to get some clarification because I was a bit confused on some points:

If using `""` for values it would allow for this when checking start date for high season on mobile app:
```
if (!timing.high_season.start.empty()) {
  // do something (DotORG) w/ start date
}
```

And if using `null` it would force the need for this:
```
if (timing != null && timing.high_season != null && !timing.high_season.start.empty()) {
  // do something (DotORG) w/ start date
}
```
Which I agree is pretty gross!

However, since we're all in agreement on adding all properties even if a value doesn't exist, my suggestion with using `null` would be more like this:
```
if (timing.high_season.start) {
  // do something (DotORG) w/ start date
}
```

The `timing`, `high_season`, `start` and `end` nested properties would all exist, but the values of `start` and `end` would just be either an ISO-8601 date or `null`.

@jonuy also mentioned that android and ios apps crap out on `null`, so it would just mean using a null check, which is still pretty similar:
```
if (timing.high_season.start !== null) {
  // do something (DotORG) w/ start date
}
```

**Comment by toidiu** [comment]
@weerd I like it! and null simply makes the most sense in some places.

**Comment by weerd** [comment]
OK! So if we're all cool with it...

Next steps include:
- update response objects output to include _ALL_ properties even if they have no value.
- if property has no value, then represent it with `NULL`

I can make these updates for `/campaign`, `/reportback`, `/reportback-items`, `/kudos` endpoints.

@uy @angaither @aaronschachter @eoji @toidiu @DFurnes

**Comment by aaronschachter** [comment]
sounds good here

**Comment by DFurnes** [comment]
Going to close this since I think this is all fixed up now! :hammer:
