### ISSUE TITLE
AWS pre-signed URL

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#154]
There was a noticeable delay in posting a user profile photo to Northstar and then actually seeing the updated photo in S3.

An alternative solution to try out is to:

1) App asks Northstar for pre-signed URL
2) App uses pre-signed URL to post photo directly to S3
3) On success, app responds back to Northstar that url was posted to successfully

http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html

**Comment by DFurnes** [comment]
I haven't heard about this happening lately, so going to close this.

References #211.
