### ISSUE TITLE
testSubmitCampaignSignup unit test is failing

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#158]
The unit test fails saying it's getting a 500 error code. The response is...
```
{
  error: {
    code: 500,
    message: "You must call Parse::initialize() before making any requests."
  },
  debug: {
    file: "/home/vagrant/sites/northstar/vendor/parse/php-sdk/src/Parse/ParseClient.php",
    line: 342
  }
}
```

I suspect this is because a signup event is triggered and we have Parse push notification code that responds to that event.

@sbsmith86 Any ideas on how this could be fixed?

**Comment by sbsmith86** [comment]
@jonuy hmm it was passing on my local. I'm calling the initialize function in the Parse service I set up: 

`ParseClient::initialize($parse_app_id, $parse_api_key, $parse_master_key);`

I wonder if I didn't set the keys correctly. Is this happening the production server?

**Comment by DFurnes** [comment]
You can mock the `ParseClient` so there aren't any external dependencies on the unit test. See the tests that mock `DrupalAPI` for an example.

**Comment by sbsmith86** [comment]
@DFurnes Ah cool, I will take a look.

**Comment by jonuy** [comment]
@sbsmith86 ah oops, I could _totally_ be doing something wrong here. If you're unable to reproduce, let me know and we can figure out what I'm doing wrong.

**Comment by jonuy** [comment]
This doesn't seem to be happening anymore. ¯\_(ツ)_/¯
