### ISSUE TITLE
Add index on User source field.

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#180]
@jonuy looking at returning specific users in aurora (DoSomething/aurora/issues/66)

We were thinking about creating an enpdoint that returns all users from a given source
Does `users?source=agg` make sense as the endpoint

**Comment by jonuy** [comment]
@angaither yea, I think that'd be fine. Do you think we'd also want to support querying against multiple sources? Something like `/users?source=agg,bgg,cgg,`?

**Comment by angaither** [comment]
yes! @jonuy great ideas!

**Comment by DFurnes** [comment]
This is something that'd be super useful for Aurora. We just need to add a MongoDB index on the `source` field, and then we can use this with existing `?filter[source]=agg,cgg` functionality.

**Comment by DeeZone** [comment]
Adding to list of requestors for this feature:

> There's a need to create MailChimp entries from mobileapp user registrations to ensure they're getting the "Weekly Do" email newsletter. This will be taken care of automagically once the `quicksilver-api` `/user/register` endpoint is in production. Until then, the plan is to create a daily batch job to collect `mobileapp` user registrations from Northstar and add them to MailChimp.

> I think I'll need a functional GET `/v1/users?filter[source]=mobileapp` type endpoint on Northstar to make this happen.

It might also be helpful to also filter by a timeframe as suggested by @DFurnes :
> I guess we’d also want to add a way to query by timeframe as well then?
