### ISSUE TITLE
Endpoint for verifying if a session token is valid

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#186]
Evan was suggesting this as an endpoint that'd be useful to have so that apps can proactively check if a user's going to use an invalid/expired token.

@weerd Is there anything you've come across in your API research that suggests a best practice for how to provide this?

**Comment by jonuy** [comment]
https://github.com/DoSomething/LetsDoThis-iOS/issues/505 would benefit from having this

**Comment by weerd** [comment]
hmmm, not that I remember offhand.

Wouldn't the app need to check the token each time and then if already logged in from prior session, but token expired the app calls like a `logout` method or something, that just brings them to the login screen?

**Comment by jonuy** [comment]
Yea, pretty much all those things will need to happen to fully implement the solution on the app side.

**Comment by DFurnes** [comment]
It might be a good idea revisit using some form of OAuth to handle this. If using [something like JWT](https://github.com/DoSomething/northstar/issues/202) for our authentication tokens, we'd include the expiration in the token.

**Comment by DFurnes** [comment]
@jonuy @aaronschachter So, returning to this issue a while later... as far as I know, tokens don't ever expire (unless the user has explicitly chosen to invalidate them). Are invalid session tokens something that we're seeing frequently?

**Comment by jonuy** [comment]
If tokens actually don't ever expire, I don't imagine this really being an issue then. I can't recall a time I've run into an invalid token, but I'm also fairly regularly logging in/out while developing. @aaronschachter is it something you've run into?

**Comment by aaronschachter** [comment]
I haven't done a bunch of testing, but I was able to get the "Token Mismatched" (https://github.com/DoSomething/LetsDoThis-iOS/issues/505#issuecomment-172057482) response after what I think was quitting the app  during the middle of a logout. 
Upon the next time I open the app,I was able to load a user's' campaigns, etc except the Token Mismatched would always return when trying to logout.  Does checking where ever we set that message in the code help give better clues how to replicate / avoid?

**Comment by DFurnes** [comment]
@aaronschachter Oh sorry, not sure how I missed this question.

The `401 Authentication token mismatched` response from Northstar gets triggered if the authentication token provided by the user (either in `Authorization` header or `Session` header) doesn't exist in the database.

The `auth/invalidate` endpoint will destroy the authentication token used to make that request, so once you make that request, the provided token cannot be used again without triggering an error.
