### ISSUE TITLE
Updating avatar photo for any user on staging only updates `test@dosomething.org` account

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/northstar#200]
Using the `POST /users/:user_id/avatar` call on staging only updates the `test@dosomething.org` account with the ID of: `POST /users/:user_id/avatar`.

**Comment by jonuy** [comment]
Turns out the bug is in the query to find the user to update with the avatar: `$user = User::where($id)->first();`

This would just give us the first user in the collection. The query should actually be: `$user = User::where("_id", $id)->first();`

Fix coming in a sec.
