### ISSUE TITLE
Use OAuth/JWT for authentication tokens

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#202]
Now that we're hooking more things into Northstar (yay!), we should probably start thinking about how we're handling authentication among multiple services.

At the moment, Northstar is able to authenticate users to itself (by providing a session token), but in order to perform authenticated requests to other services it must act as a proxy. For example, there are quite a few endpoints that use the user's Northstar session to do something on the Drupal site. As we consider adding more different services (such as a separate campaign activity API for signups & reportbacks), this gets more and more unwieldy.

From doing a bit of research, one solution seems to be granting a signed token that can be verified by any of our other services. [JSON Web Tokens](http://jwt.io) seem to be a standard way to provide a signed token (that indicates an authenticated session) which any of our internal backend services can verify. This avoids Northstar needing to act as a gatekeeper or each service needing to continually ping Northstar to check if a session is still active.

Example payload and signed token:

<img width="990" alt="screen shot 2015-08-25 at 11 39 23 am" src="https://cloud.githubusercontent.com/assets/583202/9471369/f3e4e484-4b1d-11e5-8910-14d790f59549.png">

Thoughts? @uy @angaither

**Comment by DFurnes** [comment]
This would also help with role-based authorization, since we could store user roles (like "admin" or "staff") in Northstar where they belong, but still easily make use of them elsewhere (like Aurora or the campaign activity API service).

**Comment by DFurnes** [comment]
For future reference: single sign-on for Zendesk, which is a requested feature for our Help Center, also [relies on JSON Web Tokens](https://support.zendesk.com/hc/en-us/articles/203663816-Setting-up-single-sign-on-with-JWT-JSON-Web-Token-).

**Comment by jonuy** [comment]
This sounds pretty cool. I'm struggling to grasp what the whole scope of the work here is. I'm assuming this affects at the very least Northstar and any client apps that interface with it in an authorized way. Will it need Phoenix work too? Will we eventually be pulling out the code where Northstar forwards requests onto Phoeni?

**Comment by DFurnes** [comment]
Ideally not. I think we could continue to use the same API for the mobile app with an OAuth password grant, and use a different grant and more privileged scope on products like Aurora or Phoenix that need it. (Still trying to totally understand the best way to handle this but I think that's the basic idea!)

The [lucadegasperi/oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel) package (based on the League of Extraordinary Packages's [oauth2-server](https://github.com/thephpleague/oauth2-server)) seems to be a good place for us to start. It doesn't support JWT tokens at the moment, but it seems like that's [planned for the v5 release](http://dfurn.es/1OhWxp8) of the package.

**Comment by DFurnes** [comment]
I tried setting up that package, but unfortunately it looks like it [doesn't support using MongoDB as a database store](http://dfurn.es/1NvOdTI) so we may have to hold off on this for now.

**Comment by DFurnes** [comment]
Welp, and the aforementioned pull request was rejected. So we may need to look into implementing this using the [oauth2-server](https://github.com/thephpleague/oauth2-server) package directly.

On the bright side, that Laravel package is basically just a set of migrations and a facade/auth service provider so I don't think that'd be unreasonable for us to re-implement it ourselves with MongoDB support. I think this does perhaps bring up the question of whether we're creating extra work for ourselves by using a non-standard stack but that's a discussion for another day.

**Comment by jonuy** [comment]
Could we just use a relational db to handle auth so that there isn't extra work to do? Mongo could still act as the datastore of user info, but for auth, that info is handled in a separate DB?

**Comment by DFurnes** [comment]
I'm a little wary of complicating our stack by having to maintain a SQL database (or databases) for Northstar as well but that's definitely an option.

**Comment by DFurnes** [comment]
I took a day to prototype both approaches back in mid-January, and tbh they both seemed like a lot more work than they're worth. Feel free to examine the code/diffs in the [`oauth-mongodb`](https://github.com/DoSomething/northstar/tree/oauth-mongodb) branch (which uses the League  [oauth2-server](https://github.com/thephpleague/oauth2-server) package directly), and the [`oauth-mysql`](https://github.com/DoSomething/northstar/tree/oauth-mysql) branch (which uses the Laravel-specific wrapper and an extra MySQL database connection).

Instead, I've just taken some time to make small improvements to our own homegrown authentication system. For example, it now creates token keys [using Laravel's built-in `Str::random`](https://github.com/DFurnes/northstar/commit/24ccc29d5728966e72c71fcbcc48bc3d178cd50c) (which in turn uses PHP 7's [`random_bytes`](http://php.net/manual/en/function.random-bytes.php) function and [a polyfill](https://github.com/paragonie/random_compat) in older PHP versions). We've also fixed issues with token collisions & simplified some of the implementation details of specifying a token/API key in requests.

It's not _perfect_, but I'm pretty happy with where it's at now so it's probably okay to close this.

**Comment by DFurnes** [comment]
Re-opening this because the need for an [authorization code grant](http://tools.ietf.org/html/rfc6749#section-4.1) is seeming more and more pressing as we build other services that rely on Northstar.

I found [another OAuth2 PHP library](http://bshaffer.github.io/oauth2-server-php-docs/) the other night which is definitely less elegant than the League's package but seems a bit easier to set up & includes MongoDB support out of the box. I've started experimenting with that package on the [`oauth`](https://github.com/DoSomething/northstar/tree/oauth) branch.

I have absolutely no plans to deprecate the current authentication scheme anytime soon, btw. If we do implement OAuth for our authentication backend, it could be backed by the exact same routes & data structures that we already have for the mobile app's [password grant](http://tools.ietf.org/html/rfc6749#section-4.3).

**Comment by DFurnes** [comment]
Alright, this is movin' on along! 🚂 Status update: Via #327, #330, #331, and #333 we can now authenticate users via _either_ the legacy `X-DS-REST-API-Key` and 30 character Bearer tokens, or via the new JWT Bearer tokens.

Currently, the new OAuth `/v2/auth/token` route and JWT parsing middleware are both disabled in production, pending [a PHP version update](https://git.io/vwndA) but hopefully we can flip the switch & begin testing those sometime in the next few sprints!

**Comment by DFurnes** [comment]
Going to close this since these endpoints are now live on all environments. 🌱 🌞
