### ISSUE TITLE
User campaigns cleanup

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#210]
* [x] The `reportback_data` property is only returned if a reportback exists. Refs #155 -- expected behavior would be that `reportback_data` is returned but with null value

* [x] #142 - suggest we remove the `user.campaigns` property and instead just use the `user/campaigns` endpoint, to avoid inconsistency. The user.campaigns doesn't give you reportback item url's for photos, where as the `user/campaigns` endpoint does.

* [ ] The `campaign` object only exists when the activity object has a reportback.  when no reportback exists, we only have the `drupal_id` to use as the campaign id. `drupal_id` could refer to any number of entities here (signups, reportbacks, campaign)

## With a reportback (includes `campaign`)
![screen shot 2015-10-06 at 5 45 32 pm](https://cloud.githubusercontent.com/assets/1236811/10323746/15820a3a-6c53-11e5-8f93-04691bea7d75.png)

## Without a reportback (no `campaign`)
![screen shot 2015-10-06 at 5 51 28 pm](https://cloud.githubusercontent.com/assets/1236811/10323770/32ce21a0-6c53-11e5-95aa-224ee9abb842.png)

**Comment by aaronschachter** [comment]
@DFurnes @jonuy This is higher priority now that the mobile app doesn't have a limited subset of campaigns to display. Workarounds (which don't sound like good ones) could be either to keep all ~250 campaigns loaded in memory, or making 2 requests per Profile load (one to the Northstar campaigns endpoint, and then a 2nd to Phoenix to load the relevant campaigns for each `CampaignActivity` object)

**Comment by aaronschachter** [comment]
Ideally we could expose a campaign status exposed here in the `campaign` object too, so when displaying a User’s campaigns they need to complete, we can filter any closed campaigns. Not sure how that actual sync would work (does Northstar have to query Phoenix every time to figure out whether or not the campaign has been closed?)

**Comment by DFurnes** [comment]
> The reportback_data property is only returned if a reportback exists. Refs #155 -- expected behavior would be that reportback_data is returned but with null value

Definitely. I'm working on cleaning up response formatting in #253, and (pending feedback) will be using that approach to clean up & standardize formatting of other Northstar API responses as well.

> #142 - suggest we remove the user.campaigns property and instead just use the user/campaigns endpoint, to avoid inconsistency. The user.campaigns doesn't give you reportback item url's for photos, where as the user/campaigns endpoint does.

Agreed. I think it makes less and less sense to have this as a nested property of the user object as users have more campaigns they are signed up for (now that we're including all campaigns in Northstar and the mobile app).

> The campaign object only exists when the activity object has a reportback. when no reportback exists, we only have the drupal_id to use as the campaign id. drupal_id could refer to any number of entities here (signups, reportbacks, campaign)

In the case of a `campaign` response from Northstar, `drupal_id` refers to the campaign NID. The contents of `reportback_data` [comes from the Drupal API](https://github.com/DoSomething/northstar/blob/c3112adf949c2377ff417fb37cea3c1cf9edefd9/app/Http/Controllers/CampaignController.php#L55-L60), so I wonder if cases where this is inconsistent with the expected response is just another side-effect of not having synced activity data yet?

**Comment by DFurnes** [comment]
The first two items should be taken care of now that we've merged #253, and I think the last one _should_ be fixed once we figure out activity syncing (so there aren't cases where a signup exists in Northstar but not in Drupal).

Closing this, but feel free to re-open if any of the above doesn't seem to be true! :hammer:

**Comment by DFurnes** [comment]
Hmm, it seems I lied when I said I was closing this. Closing! :closed_book:
