### ISSUE TITLE
change avatar photo calls do not work consistently 

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/northstar#211]
Both multipart and 64-bit calls frequently fail to change the stored avatar photo. 

While the calls are able to be successfully made, and do return with a `200`, the response returns with an unchanged avatar photo URL in the body. 

We've seen similar avatar photo changing weirdness before, and @jonuy suggests that this could be related to S3 latency.

**Comment by DFurnes** [comment]
I don't think this is an issue anymore. :hammer:
