### ISSUE TITLE
Migrate Northstar to HHVM

### ISSUE THREAD

**Issue by sheyd** [DoSomething/northstar#218]
- [ ] Upgrade Thor. Test.
- [ ] Upgrade Staging. Test.
- [ ] Upgrade Prod. Pray.

**Comment by DFurnes** [comment]
:pray:

**Comment by DFurnes** [comment]
@sheyd Is this still on the horizon? If not, I might close the issue for now.

**Comment by sheyd** [comment]
Yeah, it is. I've been monitoring HHVM vs PHP 7.0, and looks like HHVM is
still winning. That being said, I think PHP 7.0 is the safer choice, and
might be the win here.

**Comment by DFurnes** [comment]
Closing this since I believe we've settled on using PHP 7 for everything.
