### ISSUE TITLE
Massive New Relic Errors

### ISSUE THREAD

**Issue by sheyd** [DoSomething/northstar#221]
The error is this: `MongoClient::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known`.

It's causing between 80-100% errors on our Northstar New Relic App:

https://rpm.newrelic.com/accounts/108038/applications/12925624/traced_errors

**Comment by sheyd** [comment]
@DFurnes and I did a bunch of stuff:

* Upgraded to Laravel 5.1
* Upgraded Mongo PHP Driver
* Removed Old Laravel 4 config file (backed up to `dosomething` home dir)
* Removed a ',' after the port number in in the env file. **This one character change fixed all the errors.**

@mshmsh5000:

![screen shot 2015-10-23 at 12 08 33](https://cloud.githubusercontent.com/assets/4562565/10698397/d40c9c30-797e-11e5-862a-5927d6146afe.png)

**Comment by mshmsh5000** [comment]
Incroyable!
