### ISSUE TITLE
Bad performance on UsersController@show

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#223]
New Relic is reporting [pretty crummy performance](https://rpm.newrelic.com/accounts/108038/applications/12925624/transactions?type=app#id=5b225765625472616e73616374696f6e2f416374696f6e2f4e6f727468737461725c5c487474705c5c436f6e74726f6c6c6572735c5c55736572436f6e74726f6c6c65724073686f77222c22225d) for the [UsersController `show`](https://github.com/DoSomething/northstar/blob/16c80381b1a7ce85bf765de67947ba4b5ca4bd60/app/Http/Controllers/UserController.php#L126-L147) endpoint. From doing a little digging, it seems like this is because we don't have an index on the `drupal_id` property and so queries are _laborious_.

**Comment by DFurnes** [comment]
I added fix in #224. Going to leave this open until I can verify that response times are down in New Relic.

**Comment by DFurnes** [comment]
Yeah, much better now. :relieved: 

<img width="638" alt="screen shot 2015-10-28 at 3 45 42 pm" src="https://cloud.githubusercontent.com/assets/583202/10800911/097fd7be-7d8b-11e5-90d2-ba1bfe084e12.png">

**Comment by mshmsh5000** [comment]
:heart: :heart: :heart: :beers: :heart: :beers: :beers: :cake:
