### ISSUE TITLE
Implement DELETE on the /keys resource

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#225]
### The Ask

Allow for API keys to be deleted.

We're coming across a couple cases now where we want to delete keys.

Example: a key accidentally being made public.

#### The Task

Implement `KeyController::destroy`

**Comment by aaronschachter** [comment]
@jonuy @tongxiang Any idea on ETA for this one? It'd be really awesome to open source the LDT iOS repo for when we start reaching out to contractors...  disabling the old northstar API keys is one of the last items left to do.

**Comment by jonuy** [comment]
It's probably not a this week thing, but if we're ready to get rid of it from the LDT iOS repo, I can also just jump into the database and remove it. Are we ready to remove it?

**Comment by aaronschachter** [comment]
:fire: yep, fine to remove. thanks!

**Comment by jonuy** [comment]
@aaron the API keys for app id `ios` are now removed from prod and qa.

**Comment by DFurnes** [comment]
This is now a thing (#256)! Still need to update Aurora, but in the meantime it's possible to safely add/modify/delete API keys via the REST API. :hammer:
