### ISSUE TITLE
Drupal password checker

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#226]
### The Problem

We have a lot of users in Northstar that have a `drupal_password`, but no `password`.

**Number of accounts with a drupal_password, but no password:** 2,640,924

`db.users.find({drupal_password:{$exists:true}, password:{$exists: false}}).count()`

---

_Not sure if this information actually adds anything to the discussion, but I ran these queries anyway, so here it is..._

**Number of accounts with a drupal_password:** 2,756,471

`db.users.find({drupal_password:{$exists:true}}).count()`

**Number of accounts without a password:** 235,599

`db.users.find({password:{$exists:true}}).count()`

---

So we could feasibly run into a lot of scenarios where someone tries to login on the mobile app with the credentials they already had on the Drupal site and get an "invalid login" error.

### A Solution?

Create something in the Northstar login flow that authenticates against the user's Drupal password.

1. User sends a login request
2. If no `password` is found on the user doc, attempt to authenticate against the `drupal_password`
3. If it succeeds (or maybe even if it doesn't), copy `drupal_password` into the user's `password` field. So then for future requests, the user will have their `password` field properly filled in.
4. Allow or deny authentication like normal.

@marahml Could this be a launch blocker to the mobile app?

cc: @angaither @chloealee @DFurnes

**Comment by angaither** [comment]
yup #136 
the `drupal_password` was stored as a hashed thing, so when the user tries to auth, but there's no `password` I think we should send that auth request to drupal, and get the unhashed password and store that in Northstar so we have it for the next login

**Comment by marahml** [comment]
just chatted with @jonuy to discuss if this is a launch blocker or not. definitely will be as we're primarily driving users via a broadcast email to NZ and AU.

**Comment by chloealee** [comment]
@angaither if I hit the `POST https://www.dosomething.org/api/v1/auth/login` endpoint, it's private, so I'd have to change it to public. Is that okay? Also, it only returns the `cookie` and `token` - should I modify it to return the `user` object? I'm still not sure if I'd have access to the unhashed password this route though?

**Comment by DFurnes** [comment]
Since we have all the hashed `drupal_passwords` in Northstar, it's worth considering copying our encryption key so we can check the password hashes locally & then rehash. Otherwise we're stuck having to maintain Drupal's user database indefinitely (until we have rehashed every single user's password in Northstar).

**Comment by DFurnes** [comment]
For reference, [Drupal's password checking algorithm](https://api.drupal.org/api/drupal/includes%21password.inc/function/user_check_password/7).

**Comment by chloealee** [comment]
thanks, @DFurnes ! If we copy our encryption key in northstar, are we able to use Drupal's password checking algorithm? Or will we still have to make a call to drupal in order to use this function to check?

**Comment by DFurnes** [comment]
> If we copy our encryption key in northstar, are we able to use Drupal's password checking algorithm?

@chloealee That's the idea! The code Drupal uses for hashing passwords is pretty straightforward, and it _should_ be relatively easy to make our own hasher that could handle each of those potential types of hashes & gradually re-hash the older hashes when people log in.

**Comment by chloealee** [comment]
ah got it! So after we copy our encryption key into northstar, we can just add a block of code with the following idea into northstar's AuthController.php? 
```
    public function login(Request $request)
    {
        $input = $request->only('email', 'mobile', 'password');

        $this->validate($request, [
            'email' => 'email',
            'password' => 'required'
        ]);

        $login_type = 'username';
        if ($request->has('email')) {
            $email = strtolower($request->email);
            $user = User::where('email', '=', $email)->first();
            $login_type = 'email';
        } elseif ($request->has('mobile')) {
            $user = User::where('mobile', '=', $input['mobile'])->first();
            $login_type = 'mobile';
        }

        if (($user instanceof User) && Hash::check($input['password'], $user->password)) {
            $token = $user->login();
            $token->user = $user->toArray();

            // Return the session token with the user.
            $user->session_token = $token->key;
            $data = $user;
            return $this->respond($user);
        } else if (($user instanceof User) && !($user->password)) {
            // check to see if $input['password'] equals user's drupal password
            if (user_check_password($input['password'], $user->drupal_password)) {
                // if they're the same, re-hash $input['password'] and save it to the user
                $user->password = Hash::make($input['password']);

                $user->save();

                $token = $user->login();
                $token->user = $user->toArray();

                // Return the session token with the user.
                $user->session_token = $token->key;
                $data = $user;
                return $this->respond($user);
            }
        } else {
            throw new UnauthorizedHttpException(null, 'Invalid ' . $login_type . ' or password.');
        }
    }
```

**Comment by DFurnes** [comment]
Yup, that's the idea! Although it might be worth pulling some of this out into a new class that handles authentication... the login method is getting a bit long.

Also, it looks like Drupal's passwords might have the salt baked in to the hash (...sounds tasty :yum:) so we might not even have to worry about copying the key over. It seems like the first 3 characters of the hash specify how they're hashed, and then the next 8 are the salt.

**Comment by chloealee** [comment]
oh awesome, thanks so much for this Dave! I'll start playing around with it with this route!!
