### ISSUE TITLE
API Key scopes

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#228]
Currently, all API keys are implicitly trusted. This is a reasonable assumption when all the keys are stored server-side (such as in Phoenix or Aurora). It's potentially dangerous now that we'll have keys that are stored in client-side code (like the mobile app) and traveling over public networks.

For example, any user that finds the application ID & key by either inspecting the application bundle or sniffing HTTP traffic would be able to spoof any request that the mobile app is able to do, which includes things like creating new API keys.

We should consider adding scopes to differentiate trusted clients and "untrusted" clients.

/cc @jonuy @angaither

**Comment by jonuy** [comment]
+1 to scoping keys. But don't bundles get obfuscated in some sort of way? Though I guess anything could get decompiled and inspected. Same deal with https, I thought we'd be safe from general sniffing of packets since the data should be encrypted when being sent. But I guess there's probably something someone could do to act as a secure proxy and get the info they need.

**Comment by DFurnes** [comment]
Just for documentation, @jonuy did some digging and it turns out Android application bundles are [pretty easy](http://www.decompileandroid.com) :sweat_smile: to decompile. Luckily it shouldn't be too hard to make a quick fix, and if we get around to using a standard OAuth implementation we should get this out of the box.

**Comment by DFurnes** [comment]
And #239 is deployed to Thor now. Hopefully no issues should crop up and we can deploy this to production sometime this week. :boat:

Some other things we should lock down to `admin` scoped keys:

- [ ] Deleting users
- [ ] Seeing full profile details of other users

(Anything else that comes to mind for anyone?)

**Comment by DFurnes** [comment]
This has been running on Thor's Northstar for a while now, with no reported errors. I think we should be safe to deploy to production, and then update our `aurora` and `phoenix` API keys to have `admin` scoped privileges.

(I'd like to open an endpoint for modifying key scopes as well, but obviously would want to limit that to only be available to `admin` keys so it's a bit of a chicken-and-egg problem. :hatching_chick:)

**Comment by angaither** [comment]
:+1:

**Comment by jonuy** [comment]
:+1: As long as it's only the keys endpoint getting locked down for now (since the mobile apps use all the other endpoints), this sounds good to deploy.

**Comment by DFurnes** [comment]
> :+1: As long as it's only the keys endpoint getting locked down for now (since the mobile apps use all the other endpoints), this sounds good to deploy.

Oooof, good to double-check. I accidentally locked down `/signup-groups` as well. Made a fix in #248.

**Comment by DFurnes** [comment]
The remaining task here is to allow admin-scoped keys (or the currently authenticated user, for their own profile) to see full profile information, by conditionally adding those fields to the response [in the transformer](https://github.com/DoSomething/northstar/blob/c9ea278ec3b8509a934be94595caacc7c7840318/app/Http/Transformers/UserTransformer.php#L26-L37).

**Comment by DFurnes** [comment]
This is done! The last piece (allowing authorized users without admin-scoped keys) to view their own profile data is ready to ship in #265.
