### ISSUE TITLE
update inline comments

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#234]
just noticed these comments were off for `GET` user requests

https://github.com/DoSomething/northstar/blob/67ea51f5fba7fb777c3117c8a3326c8686b36194/app/Http/Controllers/UserController.php#L27

@chloealee @DFurnes can you take a look at these comments and others when working in NS

**Comment by chloealee** [comment]
@angaither absolutely! To fix this one, should it just be 

`GET /users?attr1=value1&attr2=value2&...`

or both 

`GET /users`
`GET /users?attr1=value1&attr2=value2&...`

**Comment by angaither** [comment]
@chloealee isn't it `/users/:term/:identifier`

**Comment by chloealee** [comment]
@angaither oohh yes you're right. Will update now and continue to look out for others!
