### ISSUE TITLE
Add Reportback Item data into the POST Reportback response

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#237]
Nice to have.
We currently need to make a 2nd API request to the Phoenix `reportbacks` endpoint (or the Northstar `user/campaigns` endpoint) after posting a Reportback to Northstar (via `user/campaigns/:campaign_id/reportback`) in order to access the newly submitted Reportback Item ID and image URL.

Current response data available:
````
{
    data =     {
        "created_at" = "2015-11-30 17:39:18";
        "drupal_id" = 1376;
        "reportback_id" = 3471;
        "reportback_source" = "letsdothis_ios";
        "signup_group" = 2936;
        "signup_id" = 2936;
        "signup_source" = "letsdothis_ios";
        "updated_at" = "2015-11-30 17:40:01";
    };
}
````

**Comment by aaronschachter** [comment]
The `drupal_id` could also be returned as a `campaign_id` to better indicate what it corresponds to (refs #210)

**Comment by DFurnes** [comment]
Since we're planning to proxy these requests through to Phoenix, this shouldn't be an issue any more (pending some [ongoing work](https://github.com/DoSomething/phoenix/pull/6118) on the Phoenix side, and the endpoints to forward those requests on this end). Closing! :hammer:

**Comment by aaronschachter** [comment]
Whoops, #270 may be better suited for the Phoenix repo then ?

**Comment by DFurnes** [comment]
Yeah, I think that's another symptom of data existing in Northstar but either not existing in Phoenix, or not being returned due to a permissions problem... can probably be solved on the Phoenix side.
