### ISSUE TITLE
Drupal registration fails on > 60 char email address

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/northstar#240]
Found via testing on the mobile app. After registering users with extremely long email addresses, the user accounts were successfully created (we were able to log into the mobile app and successfully authenticate via northstar.) 

However, after attempting to sign up for a campaign, we receive the following error, perhaps suggesting that the user wasn't successfully created on Phoenix: 
![simulator screen shot dec 7 2015 3 22 30 pm](https://cloud.githubusercontent.com/assets/5678066/11639073/7dca34fc-9cf8-11e5-8155-5c682a3059f9.png)

Discovered behavior on both staging and production while testing with email usernames that are 61 and 65 chars. A 56 char username works. 

**Accounts which fail:**
tongxiangtongxiangtongxiangtongxiangtongxiang@dosomething.org 
tongxiangtongxiangtongxiangtongxiang1234567890tongxiang@gmail.com

**Accounts which succeed:**
 tongxiangtongxiangtongxiangtongxiang1234567890@gmail.com 

Password: < the typical summer ball pasttime of DoSomething.org >

**Comment by tongxiang** [comment]
Incidentally, discovered while working on [this issue on the iOS app](https://github.com/DoSomething/LetsDoThis-iOS/issues/654#issuecomment-162592762).

**Comment by tongxiang** [comment]
Courtesy of @mshmsh5000: [Drupal's default username max length constant is 60 chars.]( https://api.drupal.org/api/drupal/modules!user!user.module/constant/USERNAME_MAX_LENGTH/7) 

A good fix on Northstar might just be adding a check for this max length.

**Comment by DFurnes** [comment]
Yeah, I think validating this in Northstar seems like a reasonable quick-fix. :+1:
