### ISSUE TITLE
Endpoint for forwarding a signup from Drupal

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#243]
See DoSomething/phoenix#4571. @chloealee is working on a `/forwardSignup` endpoint that allows us to forward a signup from Drupal into Northstar with a given `user_id`, `campaign_id`, and `signup_id`.

**Comment by DFurnes** [comment]
Just as a note for future reference, this should be locked to only `admin` scoped API keys.

**Comment by chloealee** [comment]
@DFurnes took care of this with https://github.com/DoSomething/northstar/pull/246! This issue should be closed when https://github.com/DoSomething/northstar/pull/246 is closed.

**Comment by DFurnes** [comment]
Oh, yes! Added it to the pull request. :smile:

**Comment by chloealee** [comment]
:smile:

**Comment by DFurnes** [comment]
Since we're no longer planning to store user activity in Northstar, we can close this issue! :hammer:
