### ISSUE TITLE
Re-enable New Relic Laravel integration once it's updated.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#267]
Writing this up to summarize a small Slack discussion from the API room. QA and Production servers are returning `500` errors for all requests. From the stack trace in the logs:

```
[2016-01-28 20:25:00] production.ERROR: exception 'BadMethodCallException' with message 'Method after does not exist.' in /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php:6166
Stack trace:
#0 /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php(2180): Illuminate\Routing\Router->__call('after', Array)
#1 /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php(2180): Illuminate\Routing\Router->after(Object(newrelic\Laravel\AfterFilter))
#2 /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php(2180): Illuminate\Foundation\Application->boot()
#3 /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php(1628): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#4 /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Application->bootstrapWith(Array)
#5 /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php(2303): Illuminate\Foundation\Http\Kernel->bootstrap()
#6 /var/www/northstar/releases/20160128195231/bootstrap/cache/compiled.php(2288): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#7 /var/www/northstar/releases/20160128195231/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#8 {main}  
```

Laravel 5.2 changed how events are registered, and so the `after` method on the router no longer exists. It looks like New Relic has [merged a fix into their dev branch](https://github.com/In-Touch/laravel-newrelic/pull/33/files), but not released it yet.

In the meantime, I think disabling New Relic's framework integration on Northstar's QA and production servers should stop this code from getting injected and blowing things up.

/cc @angaither @sheyd @sergii-tkachenko

**Comment by weerd** [comment]
:scream:

**Comment by sergii-tkachenko** [comment]
Northstart QA fixed by adding to `/etc/php5/fpm/conf.d/20-newrelic.ini`:

```
newrelic.framework = "no_framework"
```

**Comment by DFurnes** [comment]
Woohoo, easy! :hammer: Going to rename this issue to remind us to toggle this back on when New Relic updates their framework integration.

**Comment by sergii-tkachenko** [comment]
Turned off on prod:
```
ubuntu@ip-10-100-60-129:~$ php -i |grep newrelic.framework
newrelic.framework => no_framework => no_framework
```

**Comment by DFurnes** [comment]
It looks like the newest version of the New Relic agent [now supports Laravel 5.2](https://discuss.newrelic.com/t/php-agent-breaks-laravel-5-2/32801/30). Made a devops issue to update and then we can close this out! :racehorse:

**Comment by jessleenyc** [comment]
@DFurnes was this update ever made?

**Comment by DFurnes** [comment]
Yes!
