### ISSUE TITLE
Reportback Data in user/:id/campaigns responses depends on RB Item status

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#270]
Some of the test accounts I've used on QA for development are missing `reportback_data` in the response when a `reportback_id` exists. In the first screen shot, the reportback does exist in staging (http://staging.beta.dosomething.org/reportback/3299), but its status currently is `pending` which I believe is causing the lookup to fail.  So this is potentially a duplicate of https://github.com/DoSomething/phoenix/issues/5929... but it does seem confusing for the `reportback_data` to randomly be set to null without any indication of status. 

ID: 55fc6b09a59dbf913c8b4568
![screen shot 2016-02-04 at 10 09 06 am](https://cloud.githubusercontent.com/assets/1236811/12824732/831cd16e-cb27-11e5-8910-7792cd3a7704.png)

2nd object in https://northstar-qa.dosomething.org/v1/users/_id/567968a9a59dbf906b8b56c4/campaigns:
![screen shot 2016-02-04 at 10 05 15 am](https://cloud.githubusercontent.com/assets/1236811/12824602/d92ba45a-cb26-11e5-93ab-0ce8565d04c0.png)

**Comment by DFurnes** [comment]
I think this is another symptom of data existing in Northstar but either not existing in Phoenix, or not being returned due to a permissions problem... so it should probably be solved on the Phoenix side.

:bird:

**Comment by weerd** [comment]
@aaronschachter How are you getting that Reportback ID to begin with?

**Comment by aaronschachter** [comment]
I'm looking at the `reportback_id` property within each object :eyes:

**Comment by weerd** [comment]
Ok, so maybe better question, @DFurnes what is NS hitting on Phoenix side to get all that data? Just trying to find the point of entry so I can troubleshoot.

**Comment by DFurnes** [comment]
@weerd It's currently [hitting the `reportback-items/:id` endpoint](https://github.com/DoSomething/northstar/blob/b3625c4c2f538fce03aa5ad3020f59fd84be994b/app/Services/Phoenix.php#L264-L276) using the reportback ID stored on the Mongo campaign object.

**Comment by weerd** [comment]
ok. I'm looking into it!

**Comment by weerd** [comment]
So there definitely seems to be something failing...

![image](https://cloud.githubusercontent.com/assets/105849/12826623/e820b9be-cb49-11e5-9eea-68c8b4ad5ba1.png)

@DFurnes I'm guessing from the recent updates?

**Comment by weerd** [comment]
I might switch out the caching in that function to use the new `ApiCache` class...

**Comment by weerd** [comment]
@aaronschachter would you be able to try on Thor instead of Staging? I think Staging might be all kinds of messed up :sweat:

**Comment by aaronschachter** [comment]
Refs https://github.com/DoSomething/phoenix/issues/5929#issuecomment-182479391

We discovered today Northstar was making anonymous requests to Phoenix when loading the Reportback data. Closing this issue since this endpoint will be deprecated in https://github.com/DoSomething/northstar/pull/273, embedding Reportbacks within the Signup response should handle security issues.
