### ISSUE TITLE
Avatars aren't being stored correctly

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#272]
Via @aaronschachter in Slack:

> [2:43 PM]  howdy here - i’m getting Access Denied errors when trying to load avatars uploaded thru the mobile app. e.g. https://avatar.dosomething.org/uploads/avatars/56b4dabfa59dbf71518b4671.jpeg.  i uploaded it about an hour ago.

And via @sheyd:

> [2:51 PM] That file isn’t in `/uploads/avatars/56b4dabfa59dbf71518b4671`
> [2:52] also, he doesn’t have the `.jpeg` file extension :wink:
> [2:52] on the upload

**Comment by aaronschachter** [comment]
It does work for some of these older uploaded avatars: https://avatar.dosomething.org/uploads/avatars/55fb2d5aa59dbfa3368b4567.jpeg

**Comment by DFurnes** [comment]
@aaronschachter Out of curiosity, are you uploading avatars as files or as data URLs?

**Comment by aaronschachter** [comment]
Pretty sure we are [uploading as files]( https://github.com/DoSomething/LetsDoThis-iOS/blob/814866246c001c3f7eafbaee1c6df490fe288223/Lets%20Do%20This/Networking/DSOAPI.m#L148)

**Comment by DFurnes** [comment]
So I submitted what I hope is a fix in #283. Basically, we weren't properly parsing file extensions when uploading as data URLs and so they were getting stored improperly.

My _guess_ is that the ones that were causing trouble were submitted for testing at some point, since it seems like multipart uploads from the Android or iOS app should be a-okay from my local testing...

**Comment by DFurnes** [comment]
Going to close this for now, but give a shout if you continue to see issues. Note that broken URLs for any old avatars that were stored to users profiles will _not_ be updated until that user re-uploads their avatar.

**Comment by aaronschachter** [comment]
@DFurnes Still not working for me, just created a new account with returned photo: https://avatar.dosomething.org/uploads/avatars/56c50367a59dbf994e8b456d.jpeg

**Comment by aaronschachter** [comment]
Tested on staging and thor.

**Comment by DFurnes** [comment]
Ughhhh, bummer. :disappointed: 

I did a itty bit of troubleshooting and it seems like PHP is able to access the stored files (and isn't reporting any errors on save), but they're not appearing when accessing through the web. Will investigate more in the morning.

**Comment by aaronschachter** [comment]
@DFurnes This is working great for new users. When I am posting a new avatar to update an existing one, the `photo` property is still referring to the old file.

Newly created user, first upload:
https://avatar.dosomething.org/uploads/avatars/56cfac9ba59dbfff6a8b456f.jpeg
Go to update and the photo property returned:
https://avatar.dosomething.org/uploads/avatars/56cfac9ba59dbfff6a8b456f.jpeg

Seems we're not overwriting the file properly.... could an easy fix for this be to just write a new file, appending a counter, and set the return the new property accordingly for the given user? e.g.  https://avatar.dosomething.org/uploads/avatars/56cfac9ba59dbfff6a8b456f-1.jpeg for the 2nd upload

Refs https://github.com/DoSomething/northstar/issues/211

**Comment by DFurnes** [comment]
Hmm, yeah it looks like the images are being cached on Amazon's end & the cache isn't expiring when we overwrite an image. It's strange… I could've sworn worked when I was testing. :confused: 

Adding some sort of hash/counter to the end of the filename seems like a good fix for now. :+1:

**Comment by DFurnes** [comment]
@aaronschachter Third time's the charm? :sparkles: The fix in #288 is up on QA & Thor.
