### ISSUE TITLE
Internal server error on reporting back

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#279]
@aaronschachter reported a `500 Internal Server Error` when trying to hit the `POST reportbacks/` endpoint from the iOS app. From pointing my local Northstar instance to talk to the staging server for it's Phoenix endpoints, I'm getting the following error in the debug message:

```
Server error response [url] http:\/\/staging.beta.dosomething.org\/api\/v1\/campaigns\/1286\/reportback [status code] 500 [reason phrase] : Reportback file_url not found.
```

**Comment by DFurnes** [comment]
From the documentation for the Phoenix endpoint, it looks like `file_url` is only required if `file` (the Base-64 encoded string) isn't provided. It definitely [looks like](https://github.com/DoSomething/northstar/blob/cbcca00bb4c84a6fb255408c17ba90bc26c95e8b/app/Services/Phoenix.php#L303) we're sending this along though...

**Comment by DFurnes** [comment]
Ah, I think I got it. I [removed](https://github.com/DoSomething/northstar/pull/273/files#diff-eb9950cc3e4522e41dd68c31824f0497L220) the `'filename' => 'test123456.jpg'` parameter from the API reportback method in my changes in #273. From digging in the [Phoenix endpoint source](https://github.com/DoSomething/phoenix/blob/62106f609af0c415e97559b19b05e9394a600338/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L314) it looks like that might have been an undocumented property instructing Phoenix to save the data URL with that filename?

/cc @aaronschachter @weerd

**Comment by aaronschachter** [comment]
Good investigating @DFurnes -- I think you're right -- it does look like this is (missing from the docs) [https://github.com/DoSomething/phoenix/wiki/api#campaign-reportback]. I have a vague recollection that we needed a filename into order to get the File API's save working.. (it's been well over a year since i've looked at this code :older_man: ) 

I was using Services default endpoints as reference when I created these endpoints, which gives you back just simply the new entity id upon a POST to create. Ideally we would alter this to return the relevant Signup and Reportback responses from Transformer land... but that's a different issue.

**Comment by DFurnes** [comment]
@aaronschachter Mmm, makes sense. I put up a quick fix in #280 so this shouldn't be a blocker™.

One thing that could make sense would be having the Northstar API "automatically" perform a `GET /reportbacks/:id` on the returned string so we get the response we're expecting and then can transparently update the Phoenix endpoint later on?

**Comment by aaronschachter** [comment]
If you can get that in, it would really help! Once we report back in the mobile app, we need to display the image -- so getting that image URL in the response would be :100:

**Comment by DFurnes** [comment]
@aaronschachter Defs. That _should_ be pretty easy.

Frustratingly, the Phoenix `reportbacks/:reportback_id` function is currently returning an `{"error":{"message":"No reportback data found."}}` response on any newly created reportback ID. We're sending the admin API user credentials with the request & the reportback doesn't seem to be showing up in the Phoenix admin panel either so there might be another issue...

@weerd Is it possible the reportback API has changed with all this campaign runs work?

**Comment by weerd** [comment]
@DFurnes you need to pass in all status types you want otherwise it defaults to `approved` and `promoted`... if it's a newly added item, then it likely has a status of `pending` and you need to specify that you want that included or just the statuses you actually want ;) See if that helps?

**Comment by DFurnes** [comment]
@weerd Oh! You mentioned that once and I completely forgot. :sweat_smile: Is that only for `reportback-items` or does that apply for `reportbacks` requests as well?

**Comment by DFurnes** [comment]
Had to wrestle with Guzzle for a little bit to convince it not to run comma-delimited query string values through `urlencode`... ugh. Sadly, doesn't seem to have made any difference in the response. :disappointed:

**Comment by aaronschachter** [comment]
> Is that only for `reportback-items` or does that apply for `reportbacks` requests as well?

@weerd - It doesn't really make sense that for a single `reportbacks/:id` endpoint we'd need to pass a status value in order to get it to display... we only want a single Reportback...

**Comment by weerd** [comment]
ooooh, sorry it's for the `/reportback-items` endpoint @DFurnes :\

**Comment by aaronschachter** [comment]
@DFurnes Just checking - are you making the request to `reportbacks/:id` as an authenticated admin? Good news is I submitted a reportback on Thor and got a rbid back.

**Comment by aaronschachter** [comment]
Ooops, saw that you mention passing through the admin creds [further up the thread](https://github.com/DoSomething/northstar/issues/279#issuecomment-184735176).

This does look like something's wrong with the `reportbacks` endpoint @weerd . I logged into Thor as an admin and revisited https://thor.dosomething.org/api/v1/reportbacks/127644 and get a ""No reportback data found." message. However the reportback exists: https://thor.dosomething.org/reportback/127644

**Comment by weerd** [comment]
Ok! So yes it is a bug... sorta. It's due to this part of the code in the query... https://github.com/DoSomething/phoenix/blob/067180fd4cb233da3f31397f9144f72c1a7f2141/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.query.inc#L58-L65

Basically that section keeps flagged RBs from being returned to non-admin requests, buuuuut it doesn't account for when the `flagged` column might be `null`... just `0` or `1`. So I'm going to update it to address it and show all, regardless of flagged for admins. Cool @DFurnes @aaronschachter ?

**Comment by DFurnes** [comment]
Ahhh, tricks. That sounds reasonable to me @weerd!

**Comment by DFurnes** [comment]
@aaronschachter DoSomething/phoenix#6174 should clear up the __#blocker__ on this once it's merged, although we should definitely try to put aside time to make the same permissions updates to the `/reportbacks` index endpoint as well (see @weerd's "background context" section).
