### ISSUE TITLE
Nicer API responses for targeted action proxies

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#281]
Discussed this earlier this morning in #279 and at sprint planning. Since the "targeted actions" Services endpoints return some pretty unhelpful responses (`["3872"]`, `[false]`, etc.), let's try to normalize those and provide more helpful responses in Northstar until things can be refactored in Phoenix. :construction_worker: 

/cc @aaronschachter @jonuy

**Comment by weerd** [comment]
Yaaaaais please!

**Comment by DFurnes** [comment]
Fixed by #282! :hammer:
