### ISSUE TITLE
Add unique index to email & mobile fields

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#312]
Like, why haven't we done this yet?!?

Luckily, it seems like we've plugged the bugs that were letting this happen so we shouldn't see the issue anymore regardless, but if not it's better to fail with a constraint violation than save invalid data that we have to clean up later on! 

See [MongoDB Documentation](https://docs.mongodb.org/manual/tutorial/create-a-unique-index/).

**Comment by angaither** [comment]
cuh-ray-zay

**Comment by weerd** [comment]
:scream:
