### ISSUE TITLE
Error on Signups endpoint

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#313]
I'm getting a new error on Thor when trying to load my DS account profile 
https://northstar-thor.dosomething.org/v1/signups?user=5547be89469c64ec7d8b518d&count=200
Corresponding Phoenix:
https://thor.dosomething.org/api/v1/signups?user=1176550&count=200

and also the profile of one of my test power users:
https://northstar-thor.dosomething.org/v1/signups?user=563bb421469c64d9058b4644&count=200
Corresponding Phoenix:
https://thor.dosomething.org/api/v1/signups?user=3257305&count=200

````
{ error: 
   { code: 500,
     message: 'Client error response [url] https://thor.dosomething.org/api/v1/signups?user=3257305&count=200 [status code] 404 [reason phrase] Not Found' } }
````

**Comment by angaither** [comment]
closed with DoSomething/phoenix/pull/6279
