### ISSUE TITLE
Fix index conflict on empty strings

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#316]
We have some users that seem to have `""` saved as their email in Thor, which is causing the [unique index migration](https://github.com/DoSomething/northstar/blob/dev/database/migrations/2016_03_16_181119_AddUniqueIndexes.php) to fail when [deploying to Thor](https://app.wercker.com/#deploystep/56e9c2b6d19bbb306a0455ac). We should fix any existing accounts with this problem, and then make sure that it can't happen again! :no_bicycles:

**Comment by angaither** [comment]
:japanese_ogre:

**Comment by DFurnes** [comment]
It looks like we're also saving `null` values into these fields sometimes, and MongoDB sparse indexes only skip the unique constraint if the field flat-out doesn't exist (so two documents with `null` will conflict). Wahhh.

**Comment by DFurnes** [comment]
This is fixed on QA and Thor after a little bit of [Mongo doctoring](https://gist.github.com/DFurnes/0aa32172d135aee96a47).

I'll do the same on production on Monday. :construction_worker:

**Comment by DFurnes** [comment]
Alright, and fixed on production. :hammer:
