### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#32]
Think about the "creepy guy problem"

**Comment by jonuy** [comment]
One area to look into is with access to `/users` GET, and probably also PUT and DELETE. Any user with a regular DS account that also gets on Northstar can login with their credentials and have full access to all other actions on `/users`. A possible solution for this is to setup roles on Northstar and restrict access to endpoints based on it.

**Comment by DFurnes** [comment]
I think this is safe to close now that we've wrapped up scoping & authorization work in #228 and #265.
