### ISSUE TITLE
Update user/campaigns route

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#33]
Currently the `user/campaigns` uses query strings to say which user we are getting info from.
This should perhaps follow the `users/` show method of asking for `user/campaign/email/test@example.com`

Thoughts @jonuy

**Comment by jonuy** [comment]
To get a user, the URL is like: `users/email/test@ds.org`. So to go along those same lines, could we do something like `users/email/test@ds.org/campaigns` instead?
