### ISSUE TITLE
Add CORS header

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#332]
Working locally and getting an error: 

> Fetch API cannot load https://northstar-thor.dosomething.org/v1/signups?user=555cc065469c6430068b6dfb. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by jessleenyc** [comment]
@DFurnes was this fixed?

**Comment by DFurnes** [comment]
Nope. I think this was for an old prototype so it's not very high priority at the moment.
