### ISSUE TITLE
Migrations "failed" for #336

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#339]
Migrations ran on deploy for #336 and [were reported as successful in the Wercker deploy log](https://app.wercker.com/#deploystep/57153ae66fab89e92a02a4f4), but didn't actually perform the expected updates on either of the databases. Bummer.

**Comment by DFurnes** [comment]
@sheyd suggested that this could be because DS-Homestead is running MongoDB 2.6.11, but QA and Thor are both running MongoDB 3.2.4. That'd make sense!

**Comment by DFurnes** [comment]
In the meantime, I _think_ reverting the commits with #338 seems like a good solution until we can update DS-Homestead to be running the same MongoDB version as we use in production.

**Comment by DFurnes** [comment]
Hmm, well I updated the Homestead box to use MongoDB 3.2.x (currently 3.2.5) and re-ran the migrations from #336 and everything worked correctly. 😕 Perhaps the problem was due to using database sharding on the production servers?

**Comment by sheyd** [comment]
I'm not sure that would make a difference, since we have redundant cluster
setup, not sharding. :/ I'll see if I have some time to kick the tires on
this when I get back to the office today before Data Meeting, or Morgan or
I can help you tomorrow.

On Tue, Apr 19, 2016 at 1:09 PM, David Furnes <notifications@github.com>
wrote:

> Hmm, well I updated the Homestead box to use MongoDB 3.2.x (currently
> 3.2.5) and re-ran the migrations from #336
> <https://github.com/DoSomething/northstar/pull/336> and everything worked
> correctly. 😕 Perhaps the problem was due to using database sharding on
> the production servers?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoSomething/northstar/issues/339#issuecomment-212021511>
>



-- 
Sena Heydari
Director of Infrastructure Engineering, DoSomething.org
@alisinna

**Comment by DFurnes** [comment]
Ahh, clustering. That's what I meant, at least! 😆 Yeah, this is all very much out of my depth but it does seem weird that we keep having migration issues on the prod servers that never occur on dev.

**Comment by DFurnes** [comment]
Tried re-running the migrations with one change in #342, and unfortunately still didn't work. Strangely, copy-pasting each query into the Mongo CLI worked perfectly, so I'm a little confused what caused the issue when running through the migration.

Anyways I think this is something to keep an eye on, but don't want to spend too much time bogged down on it since there's a (hacky but decent enough) way to sidestep the problem.

**Comment by DFurnes** [comment]
Running the migrations manually worked, so closing this for now. Let's keep an eye on it though! 😬
