### ISSUE TITLE
Handle users not found on phoenix signin

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#353]
Seeing an increasing number of users who aren't created in NS (when trying to find their account https://github.com/DoSomething/phoenix/issues/6406) 

we should catch this issue and create the user if they aren't found on login.

**Comment by DFurnes** [comment]
This seems like a Phoenix issue, right?

**Comment by angaither** [comment]
oh, I thought you wanted to handle it here?

**Comment by DFurnes** [comment]
My plan was to have Phoenix attempt to create (or upsert) the user via a request to `POST users/` if the `POST users/drupal_id/:uid` request gave a 404 error for that UID. Open to other suggestions though!

**Comment by angaither** [comment]
works for me!
