### ISSUE TITLE
Simplified "search" parameter

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#354]
References DoSomething/gladiator#318.

> I've also been considering changing this endpoint to just be ?search=key and have it just automatically search by all indexes (rather than having to specify each index you want to use like search[id]=key&search[email]=key&search[mobile]=key).

This would also let us customize search logic a bit. Maybe searching by `username` (inferred email/mobile by formatting) rather than "normalizing" into each respective key, etc.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to simplify the search parameter so that we can customize our search logic.](https://trello.com/c/w1M6NcIH/139-as-a-dev-i-want-to-simplify-the-search-parameter-so-that-we-can-customize-our-search-logic)
