### ISSUE TITLE
Support multiple values for email/mobile field per user.

### ISSUE THREAD

**Issue by deezone** [DoSomething/northstar#358]
The assumption that a user will use the same email or mobile number indefinitely is not correct. Support for users changing these addresses while maintaining the relationship with the specific user of each address - past and present is needed. There may even be cases where more than one email or mobile number will be in active use with the need to understand that it's all the same person.

**Discussion from #data**:
https://dosomething.slack.com/archives/data/p1463695844000049

**Darren "Dee" Lee**

> `@nmccormick`: `@dave` `@matt` `@andrea` What should happen if a user signs up through Niche and provides an email and mobile number and one already exists in Phoenix? When attempting to create a Drupal user and there's an existing user found with the mobile number but the email is different the user creation is prevented.
> 
> Ideally the old address is maintained historically as a revision on the account but the email address gets updated which means that the MailChimp email address will also need to be updated.
> 
> I don't think we've thought through the fact that the same user can change their email and / or mobile number through time. The concern is a loss of the relationship between the different contact addresses which currently appears as two different users.
> 
> For the sake of processing current Niche users I'm considering just dealing with this situation as an existing user and not updating anything. Unfortunately this will result in us trying to communicate with the user using the old address.
> 
> OR the email address is updated and we loose the relationship and MailChimp is sending to an old account.
> 
> When we get support for changed contact addresses that maintains old values / relationships with our various services we can rerun the Niche data to build the historical relationships.
> 
> Make sense? Thoughts?

**Dave Furnes**

> I don’t think we should be changing credentials (email, mobile) on an existing account without the user’s explicit permission. Could potentially be a way for a malicious user to steal an account.
> 
> For cases where user changes one of those fields, as long as we only rely on the primary key (Northstar ID) this shouldn’t cause any issues. We should never be using email or mobile as a primary identifier for a user.
> 
> And yeah, if/once Northstar is responsible for maintaining those other service relationships it should definitely update any connected profiles using a mutator on those fields.

**Comment by DFurnes** [comment]
When you say "support historical changes in email and mobile numbers", do you mean that a user could have multiple of each of those items connected to their account (which would still count as "in use" for a uniqueness constraint)? Or just [keeping a log](https://github.com/DoSomething/northstar/issues/335) for historical reference/debugging?

As far as maintaining the relationship when an email/phone changes, that's why we only ever refer to users by their Northstar ID, since that always stays the same even if both the user's email and mobile change.

**Comment by DeeZone** [comment]
Is it as simple as supporting the update of email and mobile values in Northstar? 

- a user can have more than one active account using the same medium
- searching historical or multiple values for a communication medium will be needed to maintain / understand ongoing communication with the user.
- some services we use do not support updating contact info. ie. Update a mobile number in Mobile Commons is not possible. The historical information of what opt_in paths a number has been a part of would be lost if a user switches numbers.

**Comment by DFurnes** [comment]
We already support updating a user's email or mobile value in Northstar. We do not currently allow a user to claim more than one email or mobile number at a time, though, and I'm not sure we should without thinking carefully about any UX issues that'd introduce.

Keeping a historical record of changes made to a user's profile makes sense to me.

**Comment by DeeZone** [comment]
> Keeping a historical record of changes made to a user's profile makes sense to me.

I'd suggest a history that can easily be searched or referenced when making a query for an address to Northstar. There's a possibility that some systems will need to lookup users by historical values as their logs will be based on the user's contact values in the past.

**Comment by DeeZone** [comment]
> When you say "support historical changes in email and mobile numbers", do you mean that a user could have multiple of each of those items connected to their account (which would still count as "in use" for a uniqueness constraint)?

Yes

> that's why we only ever refer to users by their Northstar ID

Some things were built before the days of Northstar :)

**Comment by DFurnes** [comment]
> Some things were built before the days of Northstar :)

Totally! I think that going forward though, we'll avoid a lot of pain if we have a single immutable way to refer to a given user, rather than having to juggle and keep track of lots of potentially changing emails and mobile numbers.

**Comment by DeeZone** [comment]
Agreed - we've got the Quicksilver move to Northstar on the books: https://trello.com/c/jrjXgbR2 

I suppose the logging of the transactional messages could include include the Northstar ID as well. It's just going to be tricky to look at historical logs if the user has more than one email address in use and the Northstar doesn't easily provide this relationship.

**Comment by DFurnes** [comment]
Copying some more comments by @DeeZone in Slack since they're relevant to this discussion:

> I don't "have more than one active email on your account", you're right, it's not in our schema. But I have cases where it's needed. I'm trying to make a case to added it to our schema.
>
> We don't support more than one active email per account but the world operates that way. Many people have more than one active email address. Our users are signing up with both of them (via Phoenix and then via Niche, same mobile number, different email for example) and we have no way to know at the Northstar level that they're the same user.
> 
> Currently, when importing a Niche user with the same mobile as an existing Phoenix user but a different email address is ignored. The second email address is not processed in favour of the existing / older email address. We need a way to associate "all" of the addresses (emails / mobiles / OTTs) to a single Northstar user. Not three but an unlimited amount of any medium as they're all possibly currently active.

**Comment by DFurnes** [comment]
And another copy-paste from @DeeZone on Slack:

> I suspect we'll allow the user to select / update / add addresses through their Phoenix profile. Also we could message them to confirm the detection of new addresses (such as Niche import data) to give them reason to keep their profile settings current.
> 
> I think from a data perspective this issue is important to better understand who our members are. How we choose to use the information would be a question for smarter UX minds. But the choice seems fundamental.
>
> There's about 30 of the ~3000 Niche users imported in a day.

This definitely seems like something we should think about a fix for.

**Comment by DeeZone** [comment]
@jamjames An issue discussing support for more than one address (email, mobile, etc) in user profiles on Northstar.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to support multiple values for email/mobile field per user so that if a user has more than one active email, they are all associated with their northstar id.](https://trello.com/c/g1sRHPmC/140-as-a-dev-i-want-to-support-multiple-values-for-email-mobile-field-per-user-so-that-if-a-user-has-more-than-one-active-email-they)
