### ISSUE TITLE
Should we remove upsert behavior from the POST users endpoint?

### ISSUE THREAD

**Issue by DeeZone** [DoSomething/northstar#361]
When a new user request results in a new versus updated user the response code should reflect the difference - `200` vs `201`.

**Comment by DeeZone** [comment]
@DFurnes Any idea on the time frame? This is currently a blocker for Quicksilver user import implementation.

**Comment by DFurnes** [comment]
I should be able to fit it in this sprint. :)

**Comment by DeeZone** [comment]
Would it make sense to make a call to check if the user exists with **Retrieve A User** (https://github.com/DoSomething/northstar/blob/dev/documentation/endpoints/users.md#retrieve-a-user) to determine if the Niche user data is an existing user? If new, a **Create User** call could be made. 

Otherwise, as @DFurnes has pointed out, the concern of updating the user information without the user consent might happen. An example being an existing user with a known mobile number but an unknown / updated email. I don't think we want to update the email address with the Niche value with a **Create User** upsert?

**Comment by DFurnes** [comment]
Yeah, I think that could be a potential concern. I wonder if instead of "upserting" for this endpoint, we should consider having it return an unmodified existing resource if found, and then requiring the client application to make a second call to explicitly update that resource.

Perhaps if an existing account is found, it returns a `307 Temporary redirect` status code?

**Comment by DeeZone** [comment]
My understanding is `201` should be returned for "created" documents. Perhaps returning `200` with the existing user details would be a good response for **Create User** when the user already exists? Or does that create potential for confusion for the developer even when the name of the end point is very clear? 

`307` sounds kinda "funky" to me as this seems to have nothing to do with `Temporary redirect`.

**Comment by DFurnes** [comment]
Yeah, I feel like a `2xx` status code would be a bit confusing since we don't actually modify the resource in that scenario (so the request isn't really successful). It's definitely a bit funky but I think it makes decent sense based on the description in the RFC:

> ##### 10.3.8 307 Temporary Redirect
> The requested resource resides temporarily under a different URI. Since the redirection MAY be altered on occasion, the client SHOULD continue to use the Request-URI for future requests...

**Comment by DeeZone** [comment]
It feels like "*splitting hairs*" but a response of `200` suggests to me that the request (connection to the server) worked but is not a `201` as nothing was created. But that's the wonders of REST, to many interpretations. `307` works for me.

**Comment by DFurnes** [comment]
The problem that I have with `200` is that we'd also use that for updating an existing resource like `PUT /users/_id/xxxx`, since the request is successful but didn't create a new resource. I wouldn't consider this request successful if we don't persist the submitted changes.

**Comment by DeeZone** [comment]
I have a sense it's about how "*pure*" you want to be about the endpoints and the verbs you throw at them. I like this explination: http://stackoverflow.com/questions/107390/whats-the-difference-between-a-post-and-a-put-http-request

In effect the `200` response is in context of the verb. I would expect `200` from `PUT` and `POST` to mean different things. The response code is a status due to the action of the verb thus the suggested difference between `200` and `201` for **Create User (POST)**. `200` tells me the `POST / connection` was a success but a new document was not created.

But that's just my reading of the "*gospel*".

**Comment by DFurnes** [comment]
I think it's definitely up to interpretation! 😄 Either way, I think I'd like to hold off on any significant changes to how this endpoint works for a v2 of this API so we don't break existing client apps.

**Comment by DFurnes** [comment]
@DeeZone The `POST users/` endpoint now correctly returns 201 when creating new accounts (and 200 when updating the profile on an existing account) on Northstar QA & Thor! Waiting to deploy this to production until after a Phoenix deploy, since there were some related updates there as well.

Going to rename this issue so we can use it to continue the redirect discussion for a potential `v2`.

**Comment by DeeZone** [comment]
@DFurnes Does this mean we're OK with existing user data changing with the **Create User** end point? I was suggesting a `200` response would result in no change to the existing user document and the response data being the values of the existing user. 

In order to enforce your suggestion of never changing user settings without them specifically submitting the data I'll have to check if a user document exists before using this endpoint. Does this flow make sense to you?

**Comment by DFurnes** [comment]
> In order to enforce your suggestion of never changing user settings without them specifically submitting the data I'll have to check if a user document exists before using this endpoint. Does this flow make sense to you?

Yeah, I think that sounds reasonable. :thumbsup:

I'd like to avoid any big changes to how this endpoint functions for the time being because other production apps (Phoenix, Voting App) currently rely on that "upserting" behavior.

**Comment by DeeZone** [comment]
Considering the documentation title for this endpoint is "Create a User" the update functionality seems really out of place. 

Just my "two cents" 💰 ... I see all the details are in the documentation. I understand the functionality so I'll use it accordingly. Not sure how an issue like this works but perhaps it can be closed?

**Comment by DFurnes** [comment]
I'd like to leave the issue open so we can use it to continue the redirect discussion for a potential v2.

**Comment by DFurnes** [comment]
@DeeZone Another thing that occurred to me on the subway this morning, would adding an optional `?upsert=false` query parameter to allow toggling "upsert" behavior off be helpful? That'd result in a `422` validation error when matching an existing account.

**Comment by DeeZone** [comment]
@DFurnes A respnse of `422` and the details of the existing user would be ideal.

**Comment by DFurnes** [comment]
@DeeZone That PR is now deployed to Northstar QA & Thor. 😄

**Comment by DeeZone** [comment]
Looks good, let me know when it goes to production.

**Comment by DFurnes** [comment]
Yep, it was deployed a while back. 📕
