### ISSUE TITLE
Post to Quicksilver API for User Registration

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#371]
Members who register via mobile app aren't getting added to Mailchimp / Mobilecommons.

Currently blocked by not having production Quicksilver API endpoints.

**Comment by DFurnes** [comment]
@DeeZone @sergii-tkachenko I assume the [user registration](https://github.com/DoSomething/quicksilver-api/blob/master/documentation/endpoints/user.md#user-registration) endpoint is what we'll want to use here. Is that responsible for adding users to MailChimp/MobileCommons or only sending the transactional? What's the ETA on it being production ready?

**Comment by sergii-tkachenko** [comment]
First, ETA for the quicksilver to be on production and support user registration is 3 sprints.
Second, as I understand, it shouldn't be too difficult to implement an option in Phoenix to issue a transactional message to Rabbit for users, created through API.

**Comment by aaronschachter** [comment]
FWIW re: my comment about blocked by Quicksilver API endpoints -- @DeeZone had suggested using the endpoints as the ideal solution.

@DFurnes, @angaither and I were chatting yesterday about how a quick fix could potentially be to move the post to Message Broker out of the [register form submit](https://github.com/DoSomething/phoenix/blob/11f0e83f89b0e4c4eb359895e44dbe4f2c758ffb/lib/modules/dosomething/dosomething_user/dosomething_user.module#L264) and instead to an insert User hook... though I'd imagine we'd still want Northstar posting to the Quicksilver API endpoints long-term...

**Comment by angaither** [comment]
if we set the `create_drupal_user` param from here, we should be able to call [`_dosomething_user_send_to_message_broker`](https://github.com/DoSomething/phoenix/blob/11f0e83f89b0e4c4eb359895e44dbe4f2c758ffb/lib/modules/dosomething/dosomething_user/dosomething_user.module#L615) after a user is created, my only thought there is I'm not sure if `global $user` would be the northstar user that is authenticated, or the user that was created.

**Comment by DeeZone** [comment]
@DFurnes 

> Is that responsible for adding users to MailChimp/MobileCommons or only sending the transactional? 

A request to the [User Register](https://github.com/DoSomething/quicksilver-api/blob/master/documentation/endpoints/user.md#user-registration) endpoint will result in:

-  Mobile Commons signup if mobile number is present in request
- MailChimp signups 
  - Endpoint notes: "`mailchimp_list_id` determined in API based on `user_county` collected from Northstar."

**Comment by mshmsh5000** [comment]
This solution would be to handle future registrations, which is a low-volume problem (~200 per day). I don't think it's worth investing engineering beyond the Quicksilver API.

These two pieces seem adequate:

1. Finish & deploy Quicksilver API.
2. Run batch process to subscribe all past mobile registrants.

Thoughts?

**Comment by DFurnes** [comment]
@mshmsh5000 That seems like a good solution. 👍

**Comment by DeeZone** [comment]
@mshmsh5000 Sounds good.

To double clarify, once the Quicksilver-API Register User endpoint is in use by other DS applications in addition to Phoenix all MailChimp and Mobile Commons user registrations will be handled.

**Comment by mikefantini** [comment]
@mshmsh5000 this sounds good to me. Not sure when the Quicksilver API work is going to be done, but may want to run this process a few times so that people don't sit without being added to MailChimp/Mobile Commons for too long.

Doesn't seem like product has been added to this repository so can't mention folks on the team, but @mshmsh5000 if you're coordinating this batch process work can you please make sure to loop in Freddie/Kika for any welcome messaging we want to send to these app users?

**Comment by DFurnes** [comment]
@mikefantini I just added the product group to the repo so they should autocomplete now.

**Comment by mshmsh5000** [comment]
@justkika Let's discuss this in the next sprint planning.
