### ISSUE TITLE
Add CGG as an id source

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#38]
Add `cgg_id` at the top level to the user document.

**Comment by jonuy** [comment]
Sorta related to #37 and the conversation we had around this issue, what do you think about also adding a `country_code` field to the user doc?

**Comment by angaither** [comment]
I think that's already in the document

**Comment by jonuy** [comment]
![moonwalk](http://s3-ec.buzzfed.com/static/enhanced/webdr02/2013/2/6/18/anigif_enhanced-buzz-18658-1360191626-7.gif)
