### ISSUE TITLE
Add a way to filter results by timeframe.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#381]
Via some discussion in #180, it seems like it could be helpful to add the ability to narrow down queries to the user index route to only include users that were created/changed during a certain timeframe.

Perhaps something like this to get all the users created in June?

```
/v1/users?after[created_at]=2016-06-01T18:33:24+0000&before[created_at]=2016-06-30T19:33:24+0000
```

**Comment by DeeZone** [comment]
@DFurnes Is there an ETA for this item?

**Comment by DFurnes** [comment]
I just added it to track for the future. If it's blocking your backfill work, I can try to fit it in this or next sprint.

**Comment by DeeZone** [comment]
"Kinda" blocking.

A work around could be the job runs daily which processes all the returned signups from:

- `/v1/users?search[source]=mobileapp-iphone`
- `/v1/users?search[source]=mobileapp-android`

to create a sublist using the individual `created_at` values to produce daily batch.

Make sense?

**Comment by DFurnes** [comment]
Results are returned in the order they were inserted into the database, so you _should_ be safe to query for pagination details and only add the latest X pages to your batch.

I'll see if I can add in those parameters in the next sprint, since they'd be nice to have and shouldn't be super hard to implement, but hopefully that should be okay in the meantime.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to add a way to filter results by timeframe so that I have the ability to narrow down queries.](https://trello.com/c/QA72X4xS/141-as-a-dev-i-want-to-add-a-way-to-filter-results-by-timeframe-so-that-i-have-the-ability-to-narrow-down-queries)
