### ISSUE TITLE
Automatically create placeholder Phoenix accounts on registration.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#406]
See update to this issue in [my comment](https://github.com/DoSomething/northstar/issues/406#issuecomment-264937540) below.

~We should remove the `?create_drupal_user` and Northstar's code to create Drupal users – instead, these will be created on-demand the first time a user logs in to Phoenix.~

~Potential gotchas: signup, reportback, and "magic login" flows still expect a Drupal UID. We should probably update these to be possible without (or create the placeholder user on demand).~

The original-original issue:

> The `?create_drupal_user` query parameter has caused some confusion when integrating with other internal services, and doesn't really seem all that useful to have:
> 1. If a user does _not_ have a Drupal ID on their Northstar profile, we _always_ want to create a corresponding Phoenix account. The only case we wouldn't is...
> 2. If the user is coming from Phoenix (the only time we wouldn't want to make an account), they'd have a Drupal ID set (because it's [included in the payload](https://github.com/DoSomething/phoenix/blob/45f8ce9199311d4d560b2f961f503fb6c07848d1/lib/modules/dosomething/dosomething_northstar/dosomething_northstar.module#L222))
> 
> 📻

**Comment by DFurnes** [comment]
I guess one "gotcha" scenario is if when we create a mobile user without an email address: currently Northstar doesn't have logic to make `@mobile.import` placeholder Drupal emails when creating the corresponding Phoenix account.

**Comment by DFurnes** [comment]
This may also become more of a non-issue once we complete pulling auth out of Phoenix.

**Comment by DFurnes** [comment]
Going to change this issue – once we move over to using OAuth login in Phoenix, we'll want to completely disable the ability for Northstar to create Phoenix accounts.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, when oAuth is out of phoenix, I want to disable the ability for Northstar to create Phoenix accounts.](https://trello.com/c/7zCUSYma/145-as-a-dev-when-oauth-is-out-of-phoenix-i-want-to-disable-the-ability-for-northstar-to-create-phoenix-accounts)

**Comment by DFurnes** [comment]
We ran into a problem with this today on Celebs Gone Good – the voting app makes Northstar users without a password, so it doesn't create a corresponding Phoenix account. This means those users also can never signup or reportback on campaigns through Gambit. No good. 🙅‍♂️

Since we now have authentication successfully decoupled from Phoenix for a subset of users (who registered via the OpenID Connect flow & therefore only have passwords in Northstar), it makes more sense to do the same here. 

We'll update Northstar's user API endpoints to _always_ create a corresponding Phoenix accounts for new users, so any accounts created via Northstar will automatically work with the Phoenix APIs. These Phoenix users will have bogus passwords in the Phoenix database & be marked "Created By OpenID Connect", so any attempt to auth as them with Phoenix will automatically fallback to Northstar. 

For any users that have Northstar passwords set, this whole process will be transparent. For users who don't have a password field set on their account, we can send a special response to Phoenix to redirect them to the "forgot password" page.

**Comment by DFurnes** [comment]
A better long-term fix is still to have other APIs create local user accounts on demand and have the single canonical source of user data be Northstar (as described above), but that will probably end up happening in the Rogue/new front-end world rather than the ol' Droops.

**Comment by DFurnes** [comment]
This has been done, closing.
