### ISSUE TITLE
Check if sanitized phone is correct

### ISSUE THREAD

**Issue by sergii-tkachenko** [DoSomething/northstar#409]
See https://github.com/DoSomething/northstar/blob/e6255f2fbc5cd162587867adb2457c07bfd81b51/app/Models/User.php#L191

```php
        // Remove all non-numeric characters.
        $sanitizedValue = preg_replace('/[^0-9]/', '', $value);
        // If it's 11-digits and the leading digit is a 1, then remove country code.
        if (strlen($sanitizedValue) === 11 && $sanitizedValue[0] === 1) {
            $this->attributes['mobile'] = substr($sanitizedValue, 1);
            return;
        }
```

Shouldn't `$sanitizedValue[0]` be `=== '1'` (1 as string)?
As I understand, [`preg_replace()`](http://php.net/manual/en/function.preg-replace.php) returns string.

**Comment by DFurnes** [comment]
Oh yup, that is very true. 👀

**Comment by sergii-tkachenko** [comment]
Does it mean that some phones in prod data might include `1` at the beginning?

**Comment by DFurnes** [comment]
Yes. That's something that should be addressed shortly as we wrap up user data cleanup.
