### ISSUE TITLE
Implement efficient way of using openid connect drupal module

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/northstar#423]
_TASK_
@DFurnes can you fill in the blank here?

_ADDITIONAL INFO_
This task relies on the research done in: https://github.com/DoSomething/northstar/issues/422

**Comment by DFurnes** [comment]
Some running notes from @weerd & me:

 - [ ] Persist the access token & refresh token in Phoenix (right now it's only saved in memory during the request)
 - [ ] Destroy the Northstar session when the user logs out of Phoenix

🚧
