### ISSUE TITLE
Update login modal 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/northstar#426]

**Comment by DFurnes** [comment]
Just copying over some sub-tasks [from the initial experiment PR](https://github.com/DoSomething/phoenix/pull/7046#issuecomment-247376173):

 - [x] Add a feature flag for swapping out the login form. (@weerd)
 - [x] Add a `/user/openid` route so we can test OpenID login even if toggled off. (@weerd)
 - [ ] ~~Troubleshoot email conflict when authorizing as an existing Drupal account.~~ Migrate the custom `field_northstar_id` field to Drupal's `authmap` table so this module can find it.
 - [ ] Add a registration page in Northstar. (@dfurnes)
 - [ ] Persist the access token & refresh token in Phoenix between requests. (@dfurnes)
 - [ ] Destroy the Northstar session when the user logs out of Phoenix.

**Comment by DFurnes** [comment]
Another "stretch goal" that'd be nice to take care of if we extra bandwidth: we'll want to start using [Northstar-PHP](https://github.com/DoSomething/northstar/issues/426) so we can make OAuth requests from Phoenix in the future.

**Comment by mikefantini** [comment]
@DFurnes said to close this
