### ISSUE TITLE
Experiment w/ Feature Flagging 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/northstar#427]
_TASK_
Let's see what the lift is to create a feature flag for this feature. If it's small lift, let's do it. If not, let's test thoroughly on thor before we release into the wild.

**Comment by DFurnes** [comment]
This was completed in DoSomething/phoenix#7048. There's also a _secret_ 😯 route that'll allow us to test OpenID Connect on environments where it's not toggled on as the default, which was added in DoSomething/phoenix#7051.
