### ISSUE TITLE
Support passing user ID to POST Signup, Reportback

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar#429]
Add support to pass a `user` Northstar ID to allow creating a Signup and/or Reportback on [behalf of the User ID](https://github.com/DoSomething/phoenix/blob/dev/documentation/endpoints/campaigns.md#campaign-signup) passed.

Signup User ID is currently based on value passed to `Authorization: Bearer` field.

Blocks https://github.com/DoSomething/northstar-js/issues/13

**Comment by DFurnes** [comment]
This makes sense to me. We can gate this optional `user` field based on whether the user or client has admin privileges. 👍 🔏

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to support passing user ID to POST signup and reportback.](https://trello.com/c/olhRuNzg/147-as-a-dev-i-want-to-support-passing-user-id-to-post-signup-and-reportback)

**Comment by DFurnes** [comment]
Going to close this since we want applications talking directly to Rogue in the future.
