### ISSUE TITLE
Kill Aurora...?

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#433]
👹 

Aurora doesn't really seem to serve a useful purpose, since it's bounded context is the exact same as Northstar – users and authentication. This is especially true now that Northstar has it's own front-end for login and registration. Should we kill it to simplify things?

**Comment by mshmsh5000** [comment]
I'm all for simplifying. So Northstar would supply all of the admin functionality, including viewing/editing user data, etc.?

**Comment by weerd** [comment]
Yep! Not user activity data, just user profile data.

**Comment by aaronschachter** [comment]
I'm all for less repo's, but I could see us keeping Aurora as Member Profile web app, separate from the Northstar codebase. An Aurora member profile could display all the other member data that Northstar doesn't collect -- aggregating services for Campaign / SMS Activity, Notification/Subscription preferences.

Aurora came up when @sergii-tkachenko and i were chatting about pros/cons of moving Gambit 2.0 work to Sails. @sergii-tkachenko suggested Sails could work well if we need HTML (which we essentially get from the Mobile Commons UI -- but we'll want platform-agnostic views if/when we add support for other chatty services).

**Comment by DFurnes** [comment]
Yeah, that's a good point. I think having Aurora as an independent front-end would definitely make more sense if we had more services to aggregate data from.

**Comment by angaither** [comment]
we have a couple of sources 🐒 📴 🔥 💂

**Comment by weerd** [comment]
what's the monkey?

**Comment by angaither** [comment]
![](https://static.mailchimp.com/web/social/freddie.png)

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a dev, I want to kill aurora.](https://trello.com/c/ws4SPyxi/149-as-a-dev-i-want-to-kill-aurora)
