### ISSUE TITLE
Add a more user-friendly domain alias for Northstar.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/northstar#442]
This has come up in offline discussions a few times. It probably makes sense to rename Northstar's subdomain to be more user-friendly now that people will be redirected there as part of the authorization process.

Aside from being less "weird", this also would help to re-inforce the idea that you should only enter your username or password when your browser says "_____" in the address bar.

Some ideas for consideration –
- [`auth.dosomething.org`](#)
- [`profile.dosomething.org`](#)
- [`passport.dosomething.org`](#)
- [`my.dosomething.org`](#) 😏

🛂

**Comment by mshmsh5000** [comment]
`my.` also has the benefit of fewer characters, thereby conserving electrons.

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to see profile.dosomething.org in the address bar when I log in so I'm not confused by superhero names.](https://trello.com/c/tUYXkDD0/121-as-a-user-i-want-to-see-profile-dosomething-org-in-the-address-bar-when-i-log-in-so-i-m-not-confused-by-superhero-names)

**Comment by DFurnes** [comment]
References DoSomething/devops#221.

**Comment by DFurnes** [comment]
I've updated production Phoenix, Aurora, & Voting App to point to `profile.dosomething.org`. ✅
