### ISSUE TITLE
Onboarding breaking after second sign up

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/northstar#458]
_BUG_

Here's a play by play: 

1) Not signed in, click sign up for 'Patient play books'. Everything functions as expected. 
2) Click on 'explore campaigns' --> Click on 'peanut butter jam slam' --> click sign up
3) See image 1: Onboarding appears but with no reportbacks. 
4) Click 'next' --> See image 2: do not see video AND the dots that show you which slide you're on appears to highlight dot 1 when it should be highlighting dot 2
5) Click 'next' and 'prev' buttons but nothing happens. 
6) Click 'x' once (see image 3: there's an outline around the element)
7) Click 'x' one more time -- onboarding closes. 

Image 1
![screen shot 2016-10-18 at 3 07 15 pm](https://cloud.githubusercontent.com/assets/14931921/19492598/4f7f1996-9545-11e6-8f1d-606516231efb.png)

Image 2
![screen shot 2016-10-18 at 3 07 26 pm](https://cloud.githubusercontent.com/assets/14931921/19492611/5dde0b5a-9545-11e6-97ef-c38462df330a.png)

Image 3
![screen shot 2016-10-18 at 3 13 53 pm](https://cloud.githubusercontent.com/assets/14931921/19492648/80f15ec6-9545-11e6-9dcd-72e52af9f688.png)

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to push northstar to phoenix staging so that we can test oAuth and work out any bugs before going live.](https://trello.com/c/GUSjI3dA/112-as-a-developer-i-want-to-push-northstar-to-phoenix-staging-so-that-we-can-test-oauth-and-work-out-any-bugs-before-going-live)

**Comment by DFurnes** [comment]
Just as a note, I think this is a Phoenix issue (the error notices points to an undefined variable or array index in Phoenix's Northstar module).

**Comment by DFurnes** [comment]
Yeah, it looks like the `$northstar_user_info` variable on that line (used for Watchdog message) is never defined anywhere. Interesting that it only happens on the second load - perhaps we're not storing the cached version correctly?

/cc @weerd

**Comment by weerd** [comment]
Yeah, so I think I narrowed it down to an issue with how on a campaign page it tries to grab user info and pop it into the `Drupal.settings.dsUser` object, but it's coming in as `null` and causing problems. Looking into updating it so it pops that info in correctly :)
