### ISSUE TITLE
Update user password fields & e-mail addresses producing error. 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/northstar#462]
On the update profile page, users are unable to update their password or e-mail address. Error message says that the password was not provided or it was incorrect. 

From slack: 

Diego Lorenzo:
@jesslee @dave might be an openid connect thing. On local I still had setting to test with OpenID turned off, and with account I created using old flow, I was able to change password just fine.

another thing I noticed on staging is that the birthday doesn’t get passed through on the edit profile page if logged in via OpenID…

Dave Furnes:
the openid connect module sets a “fake” local password on externally-created accounts, so it’s probably best to treat that field as “wrong” once we enable this on production.

yeah, if we launch without profile page in NS we should probably remove that field in the interim
since there’s no good way to know if a password is a real user password or a fake one, afaik

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to push northstar to phoenix staging so that we can test oAuth and work out any bugs before going live.](https://trello.com/c/GUSjI3dA/112-as-a-developer-i-want-to-push-northstar-to-phoenix-staging-so-that-we-can-test-oauth-and-work-out-any-bugs-before-going-live)

**Comment by DFurnes** [comment]
Moving this issue to Phoenix, because it's a Phoenix task.
