### ISSUE TITLE
Create Northstar OAuth Credentials for Quasar ETL Machines

### ISSUE THREAD

**Issue by sheyd** [DoSomething/northstar#467]
For the Quasar platform, I need OAuth credentials to get data from the Northstar API.

**Comment by DFurnes** [comment]
You can do this using Aurora's [Create Client](https://aurora.dosomething.org/clients/create) form to make a client for our production ecosystem, or the same on [Aurora QA](https://qa-aurora.dosomething.org/clients/create) for staging/QA environment. I think using the `admin` scope is totally fine until we can get #468 moved into a sprint.

**Comment by sheyd** [comment]
Thanks @DFurnes. User setup
