### ISSUE TITLE
Unable to log user out of NS from Phoenix on first try

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/northstar#498]
This has happened to me more than once -- can't replicate EVERY time but enough to warrant a ticket. 

1) Signup for a campaign as a new user on Phoenix via NS OpenID Connect
2) Click log out 
3) Click Log in --- notice how you are auto-logged in.
4) Click log out 
5) Click log in --- behaves as expected and redirects to NS login page.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As an admin, I want to log fully log out of NS on the first try so that I'm not automatically logged in the next time I try and log in.](https://trello.com/c/fCIFQ0YE/183-as-an-admin-i-want-to-log-fully-log-out-of-ns-on-the-first-try-so-that-i-m-not-automatically-logged-in-the-next-time-i-try-and-l)

**Comment by DFurnes** [comment]
As far as I know, this hasn't happened in a long time.
