### ISSUE TITLE
Store Last Login Date in Northstar and Expose via API

### ISSUE THREAD

**Issue by sheyd** [DoSomething/northstar#543]
Analagus to Phoenix `last_logged_in` field, this piece of data will help track user activity and MAU. 

Ideally would backfill in dates from Phoenix.

**Comment by DFurnes** [comment]
This makes good sense to me! We can set this as a property on the user document whenever an account is successfully authenticated in the Registrar.

Backfilling this data from the Phoenix database would be fairly time consuming, so I'd love to think about a few scenarios where we could use that data before we commit to that process.

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a data analyst, I want Northstar to collect and add fields for `last_logged_in` and `last_accessed`](https://trello.com/c/ZG5aeGAZ/278-as-a-data-analyst-i-want-northstar-to-collect-and-add-fields-for-last-logged-in-and-last-accessed)

**Comment by DFurnes** [comment]
This is now deployed & tested in production.
