### ISSUE TITLE
Store Last Accessed Date in Northstar and Expose via API

### ISSUE THREAD

**Issue by sheyd** [DoSomething/northstar#544]
Analagus to `last_accessed` date in Phoenix. This will help track user activity in the system and MAU metric.

**Comment by DFurnes** [comment]
This makes sense – we can set this property on the user document whenever granting them a new access token (so it'll be "last accessed" with about an hour window). That seems like a fair trade-off between performance & data accuracy.

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a data analyst, I want Northstar to collect and add fields for `last_logged_in` and `last_accessed`](https://trello.com/c/ZG5aeGAZ/278-as-a-data-analyst-i-want-northstar-to-collect-and-add-fields-for-last-logged-in-and-last-accessed)

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a data analyst, I want Northstar to collect and add the field for 'last_accessed` - next quarter](https://trello.com/c/p3LREAo5/280-as-a-data-analyst-i-want-northstar-to-collect-and-add-the-field-for-lastaccessed---next-quarter)

**Comment by DFurnes** [comment]
Closed by #591.
