### ISSUE TITLE
Update error codes

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#55]
Currently all the errors are returning `401 Unauthorized`, it might be more helpful to return different codes depending on the situation and only return Unauthorized if the headers are incorrect.

**Comment by DFurnes** [comment]
Input validation errors should now be returning `422 Unprocessable entity`. We should do an audit on some of the remaining errors, and also make sure all errors are throwing through `HttpException` for standard reporting formatting. Related to #84.

**Comment by DFurnes** [comment]
This should be standardized now, closing. :hammer:
