### ISSUE TITLE
Rename `mobilecommons_status` to `mobile_status`

### ISSUE THREAD

**Issue by sergii-tkachenko** [DoSomething/northstar#570]
In order to generalize mobile accessibility status, I'd like to recommend renaming `mobilecommons_status` to `mobile_status`.

Possible values should stay the same, as declared in [northstar-mobilecommonsd](https://github.com/DoSomething/northstar-mobilecommonsd/blob/dev/app/Jobs/SendUserToNorthstar.php#L78-L87):

- `active` - For reachable users
- `undeliverable` - Invalid mobile, can't receive texts or texted STOP (note: think about re-opting-in)
- `unknown` - For everything else
- `null` for members with no mobile number. It's ok if it's not empty now for them, we can gradually change that.

As we gain access to Twilio message-level data, Blink will be able to update it on Northstar as following:

- `active` - For reachable users
- `undeliverable` - [Twilio errors](https://www.twilio.com/docs/api/rest/message#error-values) `30004`, `30005`, `30006`, or texted STOP
- `unknown` -  [Twilio errors](https://www.twilio.com/docs/api/rest/message#error-values) `30007 `, `30008`
- `null` for members with no mobile number

cc @justkika @sheyd

**Comment by DFurnes** [comment]
> In order to generalize mobile accessibility status, I'd like to recommend renaming `mobilecommons_status` to `mobile_status`.

Yeah, this makes sense to me! 👍

**Comment by aaronschachter** [comment]
Linking to https://github.com/DoSomething/gambit-conversations/issues/63 to document additional `'less'` value to indicate User's broadcast frequency preferences.

If a User texts STOP, we'll set the value to `'undeliverable'`. Per the note above about opting-in again: If user then texts us again after STOP, we will set the value to `'active'` (unless it was a STOP or LESS)

**Comment by DFurnes** [comment]
@aaronschachter Implemented this as `sms_status` in #631, including the additional `less` value. I'm leaving this as a top-level field on the user document for now, since the Laravel MongoDB package we're using makes nested fields a little complicated.

**Comment by DFurnes** [comment]
This is done, closing.
