### ISSUE TITLE
Forward registration events

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#61]
Once a user registration event occurs, Norhtstar should be responsible for sending that data over to drupal (only if the user registration event has an email attached to it)
![](https://slack-files.com/files-pub/T024GV2BW-F047GSN7H-b669c05f68/api_-_user_reg.png)

**Comment by jonuy** [comment]
I think this could also apply to user PUT/update events.

**Comment by angaither** [comment]
I think we are going to get into circular requests here, since @DeeZone is posting user registration events from the Message broker, which are sent from Drupal... it will then be sent to northstart then back to drupal :arrows_counterclockwise:

**Comment by DeeZone** [comment]
@me : confused?!?

Perhaps a stupid question but why is the User API pushing data to an app (aka Drupal). My understanding is the User API is a central store - if an app wants details it makes a request?

Should MB skip `user_registration` activities from the Drupal site? There are a few sources of user registrations beyond Drupal that I assume would be of value?

**Comment by angaither** [comment]
This api needs to send requests into Drupal because not all data is stored in Northstar. 
This route specifically needs to post to drupal so that when a user from an external app (the mobile app for instance) needs to authenticate against the app, it should be authenticating to both northstar and drupal

**Comment by jonuy** [comment]
Current plan we started going with, at least from the mobile app POV, was to have all user-related activities, including user registration, directed at Northstar. For cross platform support though, these users would also need to exist in Drupal which prompted the need to forward on registration events to Drupal.

As a possible solution to the :arrows_counterclockwise:, what if... user registrations to Northstar that include a `drupal_id` don't get forwarded onto Drupal. Seems safe to assume that Drupal already knows about this user then.
