### ISSUE TITLE
Signup/reportback forward to drupal

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#62]
When northstar gets a signup or reportback, it should forward that info along to drupal 
![](https://slack-files.com/files-pub/T024GV2BW-F047GSUSF-2834f85059/api_-_signup_reportback.png)

**Comment by jonuy** [comment]
@angaither Based on conversations we've had, it sounded like Northstar should continue to just store `sid`, `rbid` and timestamps. My thoughts are now moving towards not having Northstar forward events onto Drupal. And so from something like a mobile app's standpoint, the API requests to signup and reportback would just go directly to Drupal. Then Drupal/message broker would be responsible for pushing that to Northstar. Does this sound reasonable?

**Comment by angaither** [comment]
@jonuy I think that will just make more work for us in the future, if we decide to start storing more than the ids.
it would also make things pretty confusing if we have some endpoints forwarding into, but not others. 
Would varnish be responsible for routing signups/reportbacks into drupal?

**Comment by jonuy** [comment]
@angaither Thanks for the input. And yea, I think we'd make varnish or fastly or whatever's on that layer route those calls to Drupal. Doesn't seem like the work in this card is valid anymore, so I'll close it out.

**Comment by jonuy** [comment]
@angaither I keep forgetting this and I just remembered the other reason why we thought going this way would make sense. Drupal needs the signup and reportback POSTs to be authenticated. We don't want the mobile app to have to login to both Northstar and Drupal. Northstar could serve as that authenticated middleman between the mobile app and Drupal.

Alternatively, I imagine this can also be accomplished by the mobile app authenticating with a key and token in requests sent directly to Drupal. I don't know what work would be involved there though.

Do you have a sense of what direction to go down?

**Comment by angaither** [comment]
not really anymore :anguished:

**Comment by jonuy** [comment]
Ok, after our talk it sounds like we want to go with a variation on that first option. User is authenticated with Northstar, user sends signup or reportback to Northstar, Northstar sends this onto Drupal on the user's behalf.

In light of this, I'm going to reopen this issue.

Questions to consider:
- How will Northstar authenticate with Drupal on the user's behalf? Will Northstar just always be logged in with an admin account? Or will it be able to use an auth token of some sort?
- Does that mean having to modify the `/campaigns/:nid/signup` and `/campaigns/:nid/reportback` endpoints to support users who will be sending different info than just an `sid` or `rbid`? Or do we offer different endpoints for these two cases?

**Comment by drewish** [comment]
I think Drupal is going be happiest if the requests are authenticated as the user.

Something to consider with having Northstar proxy requests is will NS block waiting for a response for Drupal? 
If the request are syncronous I think you'll have have a lot of PHP workers.
If the requests are async you won't be able to rely on Drupal for validation, and you'll need to decide what to do with invalid requests.

**Comment by jonuy** [comment]
We're doing this proxy sort of thing currently with our SMS Node app and forwarding on report backs with seemingly good success.

All good points to consider though if we continue down this route. My two cents:
- NS doesn't block waiting for a response from Drupal. This does mean validation logic will have to be mimicked to an extent on the Northstar side. Is it wrong to think invalid requests should then just get dropped? Because that's where I'm leaning right now.

**Comment by drewish** [comment]
Ah yeah this is really the perfect type of role for a node app... that or if it's just a one way thing publish a message to rabbit.

But yeah I think it's either needing to duplicate the validation logic or just being okay with loosing input...

**Comment by jonuy** [comment]
Yea, Rabbit's a good idea. Probably not something for this initial pass unless someone's got time to kill. I don't feel too terrible about losing input here for now.

**Comment by jonuy** [comment]
@DFurnes welcome to Northstar! Some info that could help provide some more context...

Proposal for new set of sign up and reportback data that could be posted to Northstar:

**Sign Up**
This is what we've got right now on the Drupal Content API side:
https://github.com/DoSomething/dosomething/wiki/API#campaign-signup

What would make sense for Northstar to accept?
```
id: Northstar user doc id?
drupal_id: Drupal UID of user signing up. Maybe optional?
nid: Campaign node id
source: signup source - ex: android, ios
```

**Report Back**
And this is what we've got for reportbacks on the Drupal side:
https://github.com/DoSomething/dosomething/wiki/API#campaign-reportback

What would make sense here?
```
id: Northstar user doc id?
drupal_id: Drupal uid of user reporting back
nid: node nid the user is reporting back to
quantity: number of reportback nouns verbed
why_participated: reason why the user participated
file_url: image URL for the reportback?
file: Base64 encoded file string to save?
caption: caption for the reportback image.
```

Northstar would essentially then just forward this data along and store the `sid` and `rbid` returned from Drupal into the Northstar user docs.
