### ISSUE TITLE
Update user fields to also store values that message broker accepts

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#63]
This is an example user doc from message broker. Northstar should be updated to support any of the fields here that we don't currently store - particularly because message broker will start funneling its users towards Northstar as well.

```
{
    "_id" : ObjectId("540be248a593a11d23d073f4"),
    "address1" : "123 Sesame St.",
    "birthdate" : ISODate("1000-00-00T05:00:00Z"),
    "campaigns" : [
        {
            "nid" : 2461,
            "signup" : ISODate("2014-09-07T04:42:50Z"),
            "_id" : ObjectId("540be249216e3b24533e51b6")
        }
    ],
    "city" : "Westminster",
    "college_name" : "Chapman University",
    "degree_type" : "Master",
    "drupal_register_date" : ISODate("2015-03-31T21:42:35Z"),
    "drupal_uid" : 1234,
    "email" : "xxxx@gmail.com",
    "first_name" : "Big",
    "gpa" : 1.xx,
    "hs_gradyear" : 2015,
    "hs_name" : "Bolsa Grande High School",
    "last_name" : "Bird",
    "major_name" : "Economics",
    "mobile" : "1234567890",
    "race" : "A",
    "religion" : "Buddhist",
    "role" : "HSstudent",
    "sat_math" : 000,
    "sat_verbal" : 000,
    "sat_writing" : 000,
    "source" : "niche",
    "state" : "CA",
    "subscribed" : 1,
    "zip" : "99999"
}
```

**Comment by angaither** [comment]
@jonuy @DeeZone I'm not sure if we would want to store all of these fields, here's a couple I have questions about 
`role` : maybe I just don't know what the options could be here, confused by this field
`subscribed` :what does this field mean? is that mailchimp? or mobile commons? is it a list of things they are subscribed to or is it a binary option?
`source` : what is this? we have a souces id section on the user object.

**Comment by DeeZone** [comment]
Most of the additional fields are coming from niche.com user imports.
- `role` : is niche.com specific to scholarship application. I get the details if interested?
- `subscribed` : the default use email subscription preference. This is replaced / updated with:
```
subscriptions {
  mailchimp: 0 or 1
  digest: 0 or 1
  banned: 0 or 1
}
```
when one of these settings are set.
- `source` : the source of the user, typically from imports. Current possible settings are `nice`, `hercampus` or `att-ichannel`.

**Comment by angaither** [comment]
@jonuy @DeeZone 
I don't think `role` is super relevant, we might not want to save that. 
Do we want to have many ways to store the source of a user? if they don't come from another one of our apps, should we store it as a string?

**Comment by DeeZone** [comment]
Currently `source` is being logged via Message Broker in the `mb-logging-api` as:
```
    source : {
      type : String,
      lowercase : 1,
      trim : true,
      enum: ['niche', 'niche.com', 'hercampus', 'att-ichannel']
    },
```

**Comment by jonuy** [comment]
Leaving out `role` sounds reasonable.

`source`... so the intent here I think is to only store a value for `source` the first time we see this user / where the user gets registered. Because we shouldn't predict future sources or have to update this every time there is a new source, saving the value as an open-ended string as opposed to an enum seems preferable.

**Comment by angaither** [comment]
yeah, bueno.

**Comment by angaither** [comment]
add `source` field
