### ISSUE TITLE
Interest field

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#73]
make sure it can save, new items, and it's a comma separated list when things get added

```
 interests: basketball, space jam, Michael Jordon 
```

**Comment by angaither** [comment]
currently this field will overwrite anything previously in the field.
Should it be an array, or a comma separated list? The sql person in me, says comma separated list is fine, but [google](http://blog.mongodb.org/post/72874267152/transitioning-from-relational-databases-to-mongodb) seems to [disagree](http://stackoverflow.com/questions/25964521/how-to-make-a-comma-separated-list-of-array-values). 
How do we do this in laravel/mongo-land? Here's some array info
https://github.com/jenssegers/laravel-mongodb/issues/387#issuecomment-68146677

@jonuy

**Comment by jonuy** [comment]
Hm, yea this feels like a thing that should just be an array. In just straight up Mongo it'd probably be something like this: http://docs.mongodb.org/manual/reference/operator/update/addToSet/

In laravel-mongodb land, it seems like it's [supported](https://github.com/jenssegers/laravel-mongodb/blob/9603949160360173a44b46259f43ce62af76607e/src/Jenssegers/Mongodb/Query/Builder.php#L638).
