### ISSUE TITLE
Specify timezone in timestamps returned

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#85]
Currently timestamps get returned looking like: `"updated_at": "2015-04-23 16:00:51"`

We should add the timezone offset, even if 0, to be explicit about the actual time.

**Comment by DFurnes** [comment]
Timezones should all be formatted as [ISO-8601 formatted date strings](https://en.wikipedia.org/wiki/ISO_8601) in response transformers now. :hammer:
