### ISSUE TITLE
Upon registration and login, password required

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#94]
@DeeZone was getting errors that the password field was required upon registration
I think might be caused by #88

So I guess, a solution could be only login a user if the user is registered with a password?
But, for CGG, we logged in a user if they had the correct birthdate. 
this issue should probably be open for discussion

**Comment by DeeZone** [comment]
Example POST without password that results in 401 response:
![image](https://cloud.githubusercontent.com/assets/2119264/7458779/230cfaf6-f265-11e4-9a6f-851953c2d50d.png)

**Comment by angaither** [comment]
thanks @DeeZone

**Comment by jonuy** [comment]
My vote is that by default, registrations without a user password don't automatically login.

So message broker can create users without password. Mobile apps and eventually Drupal can create user with a password and also get logged in.

For cases like CGG/AGG where a user should be able to login but not ever have to supply a password, I think we'd want the business logic that determines login status to live on the client app alone. If CGG determines that a user should be logged in, then CGG is responsible requesting auth tokens for the user to use and then giving them to the user. Somewhat OAuth-like I guess.
