### ISSUE TITLE
Implement GET /campaigns/:nid/signup

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#98]
The primary purpose of this is to allow the user to get either the `sid` or `source` from her signup resource that will be used as an invite code on the mobile app.

Expected response should look something like...
```
{
  nid: 123,
  sid: 456,
  signup_source: 789,
  timestamp: 123456789
}
```

- [x] finish up #62
- [x] add `signup_source` to the campaign model
- [x] implement me

cc: @angaither

**Comment by jonuy** [comment]
Hm, probably also relies on work that'd be done here: https://github.com/DoSomething/dosomething/issues/4465

**Comment by DFurnes** [comment]
Added as `GET /campaigns/:campaign_id` per comments in #126.
