### ISSUE TITLE
Implement endpoint to get users in my Signup Group

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#99]
To support the friend/invite feature in the mobile app, this endpoint shows me who else signed up for a campaign with a shared invite code. We'd essentially query for all users who share a particular `sid` value (which is what we're using to tie groups together) in either their `sid` or `signup_source` property.

**The endpoint:**

`GET /signup-group/:sid`

**The mongo query:**

I'm basing this off of [this](http://docs.mongodb.org/manual/reference/method/db.collection.find/#query-an-array-of-documents). This probably isn't exactly right, but I think the query will look something like...
```
db.users.find({
  campaigns: {
    $elemMatch: {
      $or: [
        sid: <:sid>,
        signup_source: <:sid>
      ]
    }
  }
})
```

**The response:**

```
{
  users: [
    {
      _id,
      first_name,
      profile_image,
      sid,
      signup_source,
      rbid
    }
  ]
}
```

**Why in Northstar instead of Drupal?**

The information we need is already all here. `sid` and `signup_source` should all be here. For the facepile-like feature, user profile images will be here. For the feed of report backs from a group, each user's rbid will be here.

**Related issues:** #62, #93, #98

cc: @angaither

**Comment by aaronschachter** [comment]
Minor, it make sense to define the endpoint as a `signup-group` vs a `group` ? Group feels so vague to me, and a term we could potentially use in a million different ways e.g. Campaign Group

**Comment by aaronschachter** [comment]
Or.. is it a resource based on a signup?  `signup/:sid/group` or just an array of uid's as a property on the signup

**Comment by jonuy** [comment]
I like your idea of naming it `signup-group` instead.

With `signup/:sid/group`, I think it'd imply that `group` is a property in the signup resource, neither of which we have. In Northstar right now we've only got one collection of user documents, within which are campaign documents. Signups are just represented by its id as property of the campaign doc.

**Comment by aaronschachter** [comment]
Sounds sane to me... I think.  So for displaying the Reportbacks in a Signup Group... yes we have the rbid's stored in Northstar, so to actually display them: we query Drupal to return reportbacks for a collection of rbid's ?

**Comment by jonuy** [comment]
Either that (which doesn't exist yet) or a series of queries one `rbid` at a time.

**Comment by angaither** [comment]
same with the `source` property, that was built for an array of strings, like `niche, college prowler, etc`

should it be `signup_source` though I see how that's confusing as well...

**Comment by jonuy** [comment]
In #98 I actually did call it `signup_source` with the idea that maybe we'd also have a `reportback_source` for.. I don't know what. And it's worth noting that this is in the campaign resource, not the user resource. User resource is where the `source` property is being used for the niche, prowler, etc stuff.

**Comment by angaither** [comment]
ah, yes true. maybe not a big deal then.
